/**
 * Style Dictionary v4 config — design tokens for Vet-Rate.org.
 *
 * Source of truth: tokens/source/*.json (Style Dictionary token format).
 * Outputs (all committed so a clean clone builds without running this):
 *   - src/generated/design-tokens.css   — CSS custom properties for runtime theming
 *   - src/generated/design-tokens.js    — CJS module consumed by tailwind.config.js
 *   - docs/DESIGN_TOKENS_REFERENCE.md   — generated reference table for the docs site
 *
 * Run: `npm run build:tokens` (which calls scripts/build-tokens.mjs → npx style-dictionary).
 */

const KEBAB_NAME = ({ path }) => path.slice(1).join("-"); // drop the "color" / "size" category prefix

const tailwindShape = ({ dictionary }) => {
  // Re-build the nested `colors` object in the shape Tailwind expects:
  //   { 'service-blue': { 50: '#…', 100: '#…' }, tbi: { charcoal: '#…' } }
  const colors = {};
  dictionary.allTokens
    .filter((t) => t.path[0] === "color")
    .forEach((t) => {
      const [, family, shade] = t.path;
      if (shade === undefined) {
        colors[family] = t.value;
      } else {
        colors[family] = colors[family] || {};
        colors[family][shade] = t.value;
      }
    });
  return `/* AUTOGENERATED by scripts/build-tokens.mjs — do not edit by hand. */\n/* Source: tokens/source/*.json — run \`npm run build:tokens\` after editing tokens. */\nmodule.exports = ${JSON.stringify({ colors }, null, 2)};\n`;
};

const referenceMarkdown = ({ dictionary }) => {
  const rows = ["| Token | Value | Notes |", "|---|---|---|"];
  dictionary.allTokens.forEach((t) => {
    const name = t.path.join(".");
    const note = (t.comment || "").replace(/\|/g, "\\|");
    rows.push(`| \`${name}\` | \`${t.value}\` | ${note} |`);
  });
  return `<!-- AUTOGENERATED — do not edit. Run \`npm run build:tokens\`. Source: tokens/source/*.json. -->\n# Design tokens reference\n\n${rows.join("\n")}\n`;
};

export default {
  source: ["tokens/source/**/*.json"],
  hooks: {
    transforms: {
      "name/kebab-flat": {
        type: "name",
        transform: KEBAB_NAME,
      },
    },
    formats: {
      "javascript/tailwind-colors": tailwindShape,
      "markdown/reference": referenceMarkdown,
    },
  },
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "src/generated/",
      files: [
        {
          destination: "design-tokens.css",
          format: "css/variables",
          filter: (token) => token.path[0] !== "palettes",
          options: { outputReferences: false },
        },
      ],
    },
    "tailwind-cjs": {
      transforms: ["attribute/cti", "name/kebab-flat"],
      buildPath: "src/generated/",
      files: [
        {
          destination: "design-tokens.js",
          format: "javascript/tailwind-colors",
          filter: (token) => token.path[0] !== "palettes",
        },
      ],
    },
    "docs-md": {
      transforms: ["attribute/cti", "name/kebab-flat"],
      buildPath: "docs/",
      files: [
        {
          destination: "DESIGN_TOKENS_REFERENCE.md",
          format: "markdown/reference",
          filter: (token) => token.path[0] !== "palettes",
        },
      ],
    },
  },
  log: { warnings: "warn", verbosity: "default" },
};
