export default {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-declaration-strict-value"],
  rules: {
    "scale-unlimited/declaration-strict-value": [
      ["/color/", "fill", "stroke", "background-color", "border-color"],
      {
        ignoreValues: [
          "transparent",
          "inherit",
          "currentColor",
          "none",
          "initial",
          "unset",
        ],
      },
    ],
    "unit-allowed-list": [
      "rem",
      "em",
      "%",
      "px",
      "vw",
      "vh",
      "svh",
      "svw",
      "dvh",
      "dvw",
      "fr",
      "deg",
      "ms",
      "s",
      "ch",
      "ex",
      "vmin",
      "vmax",
      "cqi",
      "cqb",
      "cqw",
      "cqh",
      "pt",
      "in",
    ],
    "color-no-invalid-hex": true,
    "font-family-no-missing-generic-family-keyword": true,
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: [
          "tailwind",
          "apply",
          "layer",
          "screen",
          "variants",
          "responsive",
          "config",
        ],
      },
    ],
    "at-rule-prelude-no-invalid": [true, { ignoreAtRules: ["apply"] }],
    "declaration-property-value-no-unknown": [
      true,
      { ignoreProperties: { "/.*/": ["/theme\\(/"] } },
    ],
  },
  ignoreFiles: [
    "dist/**",
    "node_modules/**",
    "coverage/**",
    "src/generated/**",
  ],
};
