/**
 * useScreenshot Hook - "The Reddit Protocol"
 * 
 * Captures DOM elements as images while automatically redacting PII.
 * Uses html2canvas for capture and applies blur/blackbar to .pii-sensitive elements.
 */

import { useState, useCallback, useRef } from 'react';
import html2canvas from 'html2canvas';

/**
 * PII Detection patterns for automatic redaction
 */
const PII_PATTERNS = {
  ssn: /\b\d{3}[-\s]?\d{2}[-\s]?\d{4}\b/g,
  fileNumber: /\b[A-Z]?\d{7,9}\b/g,
  phone: /\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b/g,
  email: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g,
  dob: /\b(0?[1-9]|1[0-2])[\/\-](0?[1-9]|[12]\d|3[01])[\/\-](19|20)\d{2}\b/g,
};

/**
 * useScreenshot hook
 * 
 * @param {Object} options - Configuration options
 * @param {string} options.watermarkText - Text for watermark (default: "Generated by Vet-Rate.org")
 * @param {string} options.watermarkColor - Watermark color (default: "rgba(255,255,255,0.5)")
 * @param {boolean} options.autoRedactPII - Auto-detect and redact PII patterns (default: true)
 * @returns {Object} - Hook state and methods
 */
export const useScreenshot = (options = {}) => {
  const {
    watermarkText = 'Generated by Vet-Rate.org • Privacy Protected',
    watermarkColor = 'rgba(255, 255, 255, 0.7)',
    autoRedactPII = true,
  } = options;

  const [isCapturing, setIsCapturing] = useState(false);
  const [error, setError] = useState(null);
  const [lastCapture, setLastCapture] = useState(null);

  /**
   * Apply redaction overlay to PII-sensitive elements
   * Creates temporary black bars over .pii-sensitive elements
   */
  const applyRedactionOverlays = useCallback((targetElement) => {
    const overlays = [];
    const sensitiveElements = targetElement.querySelectorAll('.pii-sensitive, [data-pii="true"]');
    
    sensitiveElements.forEach(el => {
      const rect = el.getBoundingClientRect();
      const targetRect = targetElement.getBoundingClientRect();
      
      // Create overlay
      const overlay = document.createElement('div');
      overlay.className = 'screenshot-redaction-overlay';
      overlay.style.cssText = `
        position: absolute;
        top: ${rect.top - targetRect.top}px;
        left: ${rect.left - targetRect.left}px;
        width: ${rect.width}px;
        height: ${rect.height}px;
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #1a1a2e 100%);
        border-radius: 4px;
        z-index: 9999;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #e94560;
        font-size: 12px;
        font-weight: bold;
        letter-spacing: 1px;
        box-shadow: inset 0 0 10px rgba(233, 69, 96, 0.3);
      `;
      overlay.innerHTML = '🔒 REDACTED';
      
      overlays.push(overlay);
    });
    
    return overlays;
  }, []);

  /**
   * Add watermark to canvas
   */
  const addWatermark = useCallback((canvas) => {
    const ctx = canvas.getContext('2d');
    
    // Add semi-transparent banner at bottom
    const bannerHeight = 40;
    ctx.fillStyle = 'rgba(0, 0, 0, 0.8)';
    ctx.fillRect(0, canvas.height - bannerHeight, canvas.width, bannerHeight);
    
    // Add watermark text
    ctx.font = 'bold 14px Inter, system-ui, sans-serif';
    ctx.fillStyle = watermarkColor;
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    ctx.fillText(watermarkText, canvas.width - 20, canvas.height - bannerHeight / 2);
    
    // Add small logo/icon on left
    ctx.font = '16px sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText('🇺🇸', 20, canvas.height - bannerHeight / 2);
    
    // Add timestamp
    ctx.font = '11px Inter, system-ui, sans-serif';
    ctx.fillStyle = 'rgba(255, 255, 255, 0.5)';
    ctx.textAlign = 'left';
    ctx.fillText(new Date().toLocaleDateString(), 45, canvas.height - bannerHeight / 2);
    
    return canvas;
  }, [watermarkText, watermarkColor]);

  /**
   * Capture screenshot with redaction
   * 
   * @param {HTMLElement|React.RefObject} target - Element or ref to capture
   * @param {Object} captureOptions - Additional capture options
   * @returns {Promise<{dataUrl: string, blob: Blob}>}
   */
  const captureScreenshot = useCallback(async (target, captureOptions = {}) => {
    setIsCapturing(true);
    setError(null);

    try {
      // Get the actual DOM element
      const element = target?.current || target;
      if (!element || !(element instanceof HTMLElement)) {
        throw new Error('Invalid target element');
      }

      // Ensure element has position relative for overlays
      const originalPosition = element.style.position;
      element.style.position = 'relative';

      // Apply redaction overlays
      const overlays = applyRedactionOverlays(element);
      overlays.forEach(overlay => element.appendChild(overlay));

      // Wait for overlays to render
      await new Promise(resolve => setTimeout(resolve, 100));

      // Capture with html2canvas
      const canvas = await html2canvas(element, {
        backgroundColor: captureOptions.backgroundColor || '#1a1a2e',
        scale: captureOptions.scale || 2, // High resolution
        useCORS: true,
        allowTaint: false,
        logging: false,
        ...captureOptions,
      });

      // Remove overlays
      overlays.forEach(overlay => overlay.remove());
      element.style.position = originalPosition;

      // Add watermark
      const watermarkedCanvas = addWatermark(canvas);

      // Convert to blob and data URL
      const dataUrl = watermarkedCanvas.toDataURL('image/png', 1.0);
      const blob = await new Promise(resolve => 
        watermarkedCanvas.toBlob(resolve, 'image/png', 1.0)
      );

      const result = { dataUrl, blob, width: canvas.width, height: canvas.height };
      setLastCapture(result);
      setIsCapturing(false);
      
      return result;
    } catch (err) {
      console.error('Screenshot capture error:', err);
      setError(err.message);
      setIsCapturing(false);
      throw err;
    }
  }, [applyRedactionOverlays, addWatermark]);

  /**
   * Download the captured image
   */
  const downloadScreenshot = useCallback(async (target, filename = 'vet-rate-screenshot.png') => {
    try {
      const { blob } = target?.blob ? target : await captureScreenshot(target);
      
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      return true;
    } catch (err) {
      setError(err.message);
      return false;
    }
  }, [captureScreenshot]);

  /**
   * Copy screenshot to clipboard
   */
  const copyToClipboard = useCallback(async (target) => {
    try {
      const { blob } = target?.blob ? target : await captureScreenshot(target);
      
      await navigator.clipboard.write([
        new ClipboardItem({ 'image/png': blob })
      ]);
      
      return true;
    } catch (err) {
      setError(err.message || 'Failed to copy to clipboard');
      return false;
    }
  }, [captureScreenshot]);

  return {
    captureScreenshot,
    downloadScreenshot,
    copyToClipboard,
    isCapturing,
    error,
    lastCapture,
  };
};

export default useScreenshot;
