/**
 * The bundled verified-reference data, as generated by
 * scripts/verified-reference/build.mjs from the eCFR legal index and the
 * M21-1 shard. These pin that each required item is present and still
 * carries the words the on-device model kept getting wrong.
 */
import { describe, it, expect } from "vitest";
import reference from "../../data/verifiedReference.json";
import sections from "../../data/cfrSections.json";

const entry = (id) => reference.entries.find((e) => e.id === id);

describe("verifiedReference.json", () => {
  it("holds every required regulation, the PACT lists and the forms table", () => {
    expect(reference.entries.map((e) => e.id)).toEqual([
      "cfr-3.155-b",
      "cfr-3.155-b-1",
      "cfr-3.310-a",
      "cfr-3.310-b",
      "cfr-3.310-c-d",
      "cfr-3.2501",
      "cfr-3.2501-a-d",
      "cfr-4.16-a",
      "cfr-4.16-b",
      "cfr-4.16-a-employment",
      "cfr-4.25",
      "cfr-4.25-a",
      "cfr-4.25-b",
      "cfr-4.26",
      "cfr-4.26-a-b-d",
      "pact-toxic-conditions",
      "pact-toxic-service",
      "pact-toxic-rule",
      "pact-herbicide-conditions",
      "pact-herbicide-service",
      "pact-herbicide-law-changes",
      "va-forms",
    ]);
  });

  it.each(reference.entries)(
    "$id records its citation, source file and source date",
    (e) => {
      expect(e.citation).toBeTruthy();
      expect(e.sourceLabel).toBeTruthy();
      expect(e.text.trim().length).toBeGreaterThan(100);
      expect(e.source.file).toMatch(/^public\/(legal-index|dkb-index)\//);
      expect(e.source.retrieved).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(e.text).not.toContain("Editorial Note");
    },
  );

  it("quotes the rules the model misstated", () => {
    expect(entry("cfr-3.155-b").text).toContain(
      "within 1 year of receipt of the intent to file a claim, VA will consider the complete claim filed as of the date the intent to file a claim was received",
    );
    expect(entry("cfr-3.310-a").text).toContain(
      "disability which is proximately due to or the result of a service-connected disease or injury shall be service connected",
    );
    expect(entry("cfr-3.2501").text).toContain("new and relevant evidence");
    expect(entry("cfr-4.16-a").text).toContain(
      "this disability shall be ratable at 60 percent or more",
    );
    expect(entry("cfr-4.16-a").text).toContain(
      "at least one disability ratable at 40 percent or more, and sufficient additional disability to bring the combined rating to 70 percent or more",
    );
    expect(entry("cfr-4.16-b").text).toContain("extra-schedular consideration");
    expect(entry("cfr-4.25-b").text).toContain(
      "will be done only once per rating decision",
    );
    expect(entry("cfr-4.26").text).toContain(
      "10 percent of this value will be added (i.e., not combined)",
    );
    expect(entry("cfr-4.26").text).toContain("in each of 2 paired extremities");
  });
});

describe("verifiedReference.json PACT Act lists and forms", () => {
  it("carries the PACT Act conditions, locations and dates from the M21-1", () => {
    expect(entry("pact-toxic-conditions").text).toContain(
      "Under 38 U.S.C. 1120, the recognized presumptive conditions are",
    );
    expect(entry("pact-toxic-conditions").text).toContain("glioblastoma");
    expect(entry("pact-toxic-service").text).toContain(
      "Active service on or after August 2, 1990",
    );
    expect(entry("pact-toxic-service").text).toContain(
      "Active service on or after September 11, 2001",
    );
    expect(entry("pact-herbicide-conditions").text).toContain("hypertension");
    expect(entry("pact-herbicide-service").text).toContain(
      "January 9, 1962, to June 30, 1976",
    );
    expect(entry("pact-toxic-rule").source.changeDate).toBe("June 6, 2025");
  });

  it("spells out only the abbreviations the source article defines", () => {
    expect(entry("pact-toxic-rule").abbreviations).toEqual([
      { short: "SC", long: "service connection" },
      {
        short: "BPOT",
        long: "burn pits and other toxins, including fine particulate matter",
      },
    ]);
    expect(entry("pact-herbicide-service").abbreviations).toEqual([]);
  });

  it("lists the key claim forms by number and official title", () => {
    const forms = entry("va-forms");
    expect(forms.forms.map((f) => f.number)).toEqual([
      "21-526EZ",
      "21-0966",
      "20-0995",
      "20-0996",
      "10182",
      "21-4138",
      "21-10210",
      "21-0781",
      "21-8940",
      "21-4192",
      "21-4142",
      "21-4142a",
      "21-22",
      "21-22a",
      "21-686c",
      "21-2680",
    ]);
    expect(forms.text).toContain(
      "VA Form 21-526EZ: Application for Disability Compensation and Related Compensation Benefits",
    );
    expect(forms.text).toContain(
      "VA Form 21-0966: Intent to File a Claim for Compensation and/or Pension, or Survivors Pension and/or DIC",
    );
    expect(forms.text).toContain(
      "VA Form 20-0995: Decision Review Request: Supplemental Claim",
    );
    expect(forms.text).toContain(
      "VA Form 20-0996: Decision Review Request: Higher-Level Review",
    );
    expect(forms.text).toContain(
      "VA Form 10182: Decision Review Request: Board Appeal (Notice of Disagreement)",
    );
    expect(forms.forms.every((f) => f.mentions >= 2)).toBe(true);
  });
});

describe("cfrSections.json", () => {
  const all = new Set([...sections.parts[3], ...sections.parts[4]]);

  it("records where the list came from", () => {
    expect(sections.source.file).toBe(
      "public/legal-index/v0.1.0/chunks/ecfr.jsonl",
    );
    expect(sections.source.retrieved).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it("contains real Part 3 and Part 4 sections", () => {
    for (const section of [
      "3.1",
      "3.155",
      "3.310",
      "3.320a",
      "3.2501",
      "4.16",
      "4.25",
      "4.26",
      "4.71a",
      "4.130",
    ]) {
      expect(all.has(section), section).toBe(true);
    }
  });

  it("does not contain sections that do not exist", () => {
    for (const section of ["4.37", "4.71b", "4.90", "3.9999", "4.131"]) {
      expect(all.has(section), section).toBe(false);
    }
  });
});
