/**
 * src/data/verifiedQuotes.json, generated by
 * scripts/verified-reference/build.mjs: the decision review options and the
 * sentences that answer corrections quote. Every quotation must also appear
 * in the bundled entry it was taken from.
 */
import { describe, it, expect } from "vitest";
import quotes from "../../data/verifiedQuotes.json";
import reference from "../../data/verifiedReference.json";

const allEntryText = reference.entries
  .map((e) => e.text)
  .join("\n")
  .replaceAll("\n", " ");

describe("review options", () => {
  const { lead, lanes } = quotes.reviewOptions;

  it("opens with the one-year rule of 38 CFR 3.2500(a)(1)", () => {
    expect(lead.citation).toBe("38 CFR § 3.2500(a)(1)");
    expect(lead.text).toContain(
      "Within one year from the date on which the agency of original jurisdiction issues a notice of a decision",
    );
  });

  it("lists the three lanes with their form numbers and official titles", () => {
    expect(lanes.map((lane) => [lane.id, lane.form.number])).toEqual([
      ["higher-level-review", "20-0996"],
      ["board-appeal", "10182"],
      ["supplemental-claim", "20-0995"],
    ]);
    expect(lanes.map((lane) => lane.form.title)).toEqual([
      "Decision Review Request: Higher-Level Review",
      "Decision Review Request: Board Appeal (Notice of Disagreement)",
      "Decision Review Request: Supplemental Claim",
    ]);
  });

  it("quotes the rule that sets each lane apart", () => {
    const text = (id) =>
      lanes
        .find((lane) => lane.id === id)
        .quotes.map((q) => q.text)
        .join(" ");
    expect(text("higher-level-review")).toContain(
      "the higher-level adjudicator may not consider additional evidence",
    );
    expect(text("board-appeal")).toContain(
      "The Notice of Disagreement must be filed with the Board of Veterans' Appeals",
    );
    expect(text("supplemental-claim")).toContain(
      "At any time after VA issues notice of a decision on an issue within a claim, a claimant may file a supplemental claim",
    );
  });

  it("never mentions a Statement of the Case", () => {
    expect(JSON.stringify(quotes.reviewOptions)).not.toMatch(
      /statement of the case/i,
    );
  });
});

describe("correction quotes", () => {
  it("has one quote for each correction the answer checks can make", () => {
    expect(Object.keys(quotes.corrections)).toEqual([
      "secondary",
      "tdiu-judgment",
      "tdiu-extra-schedular",
      "presumptive-herbicide",
      "presumptive-toxic",
      "presumed-toxic-exposure",
      "presumed-herbicide-exposure",
      "higher-level-review-evidence",
      "higher-level-review-conference",
      "review-period-start",
      "ratings-combined",
      "supplemental-any-time",
      "new-and-relevant",
      "claim-has-its-own-date",
      "review-filing",
    ]);
  });

  it.each(Object.entries(quotes.corrections))(
    "%s carries a citation, a source date and one whole quotation",
    (_id, quote) => {
      expect(quote.citation).toBeTruthy();
      expect(quote.source.retrieved).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(quote.text.length).toBeGreaterThan(60);
      expect(quote.text).not.toContain("[...]");
    },
  );

  it.each([
    "secondary",
    "tdiu-judgment",
    "tdiu-extra-schedular",
    "presumptive-toxic",
    "presumed-toxic-exposure",
    "supplemental-any-time",
    "new-and-relevant",

    "review-filing",
  ])("%s is word for word in the text the model was given", (id) => {
    expect(allEntryText).toContain(quotes.corrections[id].text);
  });

  it("quotes the sentences the corrections rely on", () => {
    const { corrections } = quotes;
    expect(corrections.secondary.text).toContain(
      "disability which is proximately due to or the result of a service-connected disease or injury shall be service connected",
    );
    expect(corrections["tdiu-judgment"].text).toContain(
      "in the judgment of the rating agency, unable to secure or follow a substantially gainful occupation",
    );
    expect(corrections["tdiu-extra-schedular"].text).toContain(
      "for extra-schedular consideration all cases of veterans who are unemployable",
    );
    expect(corrections["presumptive-herbicide"].text).toContain(
      "even though there is no record of such disease during service",
    );
    expect(corrections["presumed-toxic-exposure"].text).toContain(
      "VA will presume BPOT exposure",
    );
  });
});
