/**
 * A synthetic OCR page in the layout of a Guard/Reserve-era DD-214 scan read in
 * columns: the form title is cut after "DISCHARGE F" and its tail "ROM ACTIVE
 * DUTY" lands under box 2's label; box 2's value, box 13's second half and box
 * 28's value are printed far from their labels; box 29 has stray marks beside
 * its value. Every value is invented; the shapes follow the records
 * verifier's description of the real scan.
 */
export const COMPONENT_TOKEN = "ARNGUS";
export const REASON = "COMPLETION OF REQUIRED ACTIVE SERVICE";
export const COURSE = "WARRIOR LEADER TRAINING COURSE, 4 WEEK, 2009";

export const AWARD_NAMES = [
  "ALPHA SERVICE MEDAL",
  "BRAVO ACHIEVEMENT RIBBON",
  "CHARLIE CAMPAIGN STAR",
  "DELTA TRAINING RIBBON",
  "ECHO UNIT CITATION",
  "FOXTROT GOOD CONDUCT MEDAL",
  "GOLF EXPEDITIONARY MEDAL",
  "HOTEL MERIT AWARD",
  "INDIA OVERSEAS RIBBON",
  "JULIET VOLUNTEER MEDAL",
  "KILO RESPONSE MEDAL",
  "LIMA PURPLE HEART",
];

const FIRST_AWARDS_FRAGMENT =
  "ALPHA SERVICE MEDAL-2//BRAVO ACHIEVEMENT RIBBON-1//CHARLIE CAMPAIGN";

const SECOND_AWARDS_FRAGMENT = [
  "STAR/DELTA TRAINING RIBBON//ECHO UNIT CITATION/FOXTROT GOOD",
  'CONDUCT MEDAL-3//GOLF EXPEDITIONARY MEDAL W/ "M" DEVICE-2/IHOTEL',
  "MERIT AWARD//INDIA OVERSEAS RIBBON//JULIET VOLUNTEER MEDAL/KILO RESPONSE MEDAL/LIMA",
  "",
  "PURPLE HEART//INOTHING FOLLOWS",
].join("\n");

export const GUARD_RESERVE_SCAN = [
  "=== DD214 DOCUMENT 1: sample.pdf ===",
  "(File type: pdf, Method: advanced_ocr, Pages: 1)",
  "",
  "--- PAGE 1 (OCR 83%) ---",
  "THIS 'S AN IMPORTANT RECCRD",
  "SAFEGUARD IT",
  "",
  "CERTIFICATE OF RELEASE OR DISCHARGE F",
  "",
  "9 COMMAND TO WHICH TRANSFERRED",
  "REVERT TO ARNGUS OF TESTSTATE",
  "",
  "13. DECORATIONS, MEDALS. BADGES, CITATIONS AD CAMPAIGN RIBBONS AWARDED OR AUTHORIZED       Ag                  )",
  FIRST_AWARDS_FRAGMENT,
  "",
  "DUTY ASSIGNMENT AND MAJOR COMMAND",
  "",
  COMPONENT_TOKEN,
  "",
  ":           :          5. DATE OF BIRTH (YYYYMMDD)",
  "OF RECORD AT TIME OF ENTR",
  "",
  "7.b HOME",
  "",
  "a. Date entered AD This",
  "",
  "2. DEPARTMENT, COMPONENT AND BRANCH",
  "",
  "ANY ALTERATIUNDS iN dnmucy",
  "AREAS RENDER FORM vOID",
  "",
  "ROM ACTIVE DUTY",
  "",
  "3. SOCIAL SECURITY NO.",
  "",
  "12 RECORD OF SERVICE       [Vear(s) | Month(s) |  Day(s)",
  "'d. Total Prior Active Service",
  "",
  "ERap———— Se",
  "",
  "eriods of service",
  "",
  SECOND_AWARDS_FRAGMENT,
  "",
  "14. MILITARY EDUCATION (Course. title, number of weeks and month and year ccmpleted)",
  `${COURSE}//INOTHING FOLLOWS`,
  "",
  "VETERANS EDUCATIONAL ASSISTANCE PROGRAM",
  "",
  "15 a MEMBER CONTRIBUTED TO POST-VIETNAM ERA         |",
  "",
  "155 HIGH SCHOOL GRADUATE OR",
  "EQUIVALENT",
  "",
  "18. REMARKS            :",
  "SAMPLE REMARK ONE",
  "",
  "23. TYPE OF SEPARATION =    =",
  "'REVERT TO RESERVE",
  "",
  "28. NARRATIVE REASON FOR SEPARATION",
  "",
  "LING ADDRESS AFTER SEPARATION. (Inclu",
  "",
  "SAMPLE REMARK TWO//SAMPLE REMARK THREE",
  "SAMPLE REMARK FOUR/SAMPLE REMARK FIVE                                                     NO             sles",
  "",
  "—SECIAL ADDITIONAL INFORMATION (for use by authorized",
  "—     24. CHARACTER OF SE",
  "",
  "HONORABLE",
  "",
  `| "${REASON} |`,
  "",
  "29. DATES OF TIME LOST DURING THIS PERIOD",
  "NONE                   -",
  "",
  "DD FORM 514-AUTOMATED, NOV 88",
  "",
  "Previous editions are obsolete",
  "",
  "[Yes | No | 16 DAYS ACCRUED LEAVE PAID",
  "",
  "S AND TREATMENT WITHIN 90 DAYS PRIOR TO SEPARATION            [Tees] x ef",
  "",
  "agencies only)",
  "RVICE (Include upgrades)",
  "",
  "30. MEMBER REQUESTS COPY 4",
  "MEMBER - 4",
].join("\n");
