/**
 * Vet-Rate.org - Ribbon Rack Data Utilities
 * ==========================================
 *
 * DD214 Parser, Precedence Sorter, and Device Handler
 *
 * This module provides:
 * 1. parseDD214Text() - Extract awards from DD214 text
 * 2. sortRibbonsByPrecedence() - Sort by branch-specific order
 * 3. Device attachment logic for visual rendering
 */

// Import the scraped manifest (generated by ribbon_scraper.py)
import ribbonManifest from "../data/ribbon_manifest.json";

// Import every researched state/territory National Guard award file. Each
// file's `awards` array already carries scope:"state" and stateCode, and
// gets merged into MASTER_AWARDS below alongside the federal manifest.
import stateAwards_AK from "../data/stateAwards/AK.json";
import stateAwards_AL from "../data/stateAwards/AL.json";
import stateAwards_AR from "../data/stateAwards/AR.json";
import stateAwards_AZ from "../data/stateAwards/AZ.json";
import stateAwards_CA from "../data/stateAwards/CA.json";
import stateAwards_CO from "../data/stateAwards/CO.json";
import stateAwards_CT from "../data/stateAwards/CT.json";
import stateAwards_DC from "../data/stateAwards/DC.json";
import stateAwards_DE from "../data/stateAwards/DE.json";
import stateAwards_FL from "../data/stateAwards/FL.json";
import stateAwards_GA from "../data/stateAwards/GA.json";
import stateAwards_GU from "../data/stateAwards/GU.json";
import stateAwards_HI from "../data/stateAwards/HI.json";
import stateAwards_IA from "../data/stateAwards/IA.json";
import stateAwards_ID from "../data/stateAwards/ID.json";
import stateAwards_IL from "../data/stateAwards/IL.json";
import stateAwards_IN from "../data/stateAwards/IN.json";
import stateAwards_KS from "../data/stateAwards/KS.json";
import stateAwards_KY from "../data/stateAwards/KY.json";
import stateAwards_LA from "../data/stateAwards/LA.json";
import stateAwards_MA from "../data/stateAwards/MA.json";
import stateAwards_MD from "../data/stateAwards/MD.json";
import stateAwards_ME from "../data/stateAwards/ME.json";
import stateAwards_MI from "../data/stateAwards/MI.json";
import stateAwards_MN from "../data/stateAwards/MN.json";
import stateAwards_MO from "../data/stateAwards/MO.json";
import stateAwards_MS from "../data/stateAwards/MS.json";
import stateAwards_MT from "../data/stateAwards/MT.json";
import stateAwards_NC from "../data/stateAwards/NC.json";
import stateAwards_ND from "../data/stateAwards/ND.json";
import stateAwards_NE from "../data/stateAwards/NE.json";
import stateAwards_NH from "../data/stateAwards/NH.json";
import stateAwards_NJ from "../data/stateAwards/NJ.json";
import stateAwards_NM from "../data/stateAwards/NM.json";
import stateAwards_NV from "../data/stateAwards/NV.json";
import stateAwards_NY from "../data/stateAwards/NY.json";
import stateAwards_OH from "../data/stateAwards/OH.json";
import stateAwards_OK from "../data/stateAwards/OK.json";
import stateAwards_OR from "../data/stateAwards/OR.json";
import stateAwards_PA from "../data/stateAwards/PA.json";
import stateAwards_PR from "../data/stateAwards/PR.json";
import stateAwards_RI from "../data/stateAwards/RI.json";
import stateAwards_SC from "../data/stateAwards/SC.json";
import stateAwards_SD from "../data/stateAwards/SD.json";
import stateAwards_TN from "../data/stateAwards/TN.json";
import stateAwards_TX from "../data/stateAwards/TX.json";
import stateAwards_UT from "../data/stateAwards/UT.json";
import stateAwards_VA from "../data/stateAwards/VA.json";
import stateAwards_VI from "../data/stateAwards/VI.json";
import stateAwards_VT from "../data/stateAwards/VT.json";
import stateAwards_WA from "../data/stateAwards/WA.json";
import stateAwards_WI from "../data/stateAwards/WI.json";
import stateAwards_WV from "../data/stateAwards/WV.json";
import stateAwards_WY from "../data/stateAwards/WY.json";

const STATE_AWARD_FILES = [
  stateAwards_AK,
  stateAwards_AL,
  stateAwards_AR,
  stateAwards_AZ,
  stateAwards_CA,
  stateAwards_CO,
  stateAwards_CT,
  stateAwards_DC,
  stateAwards_DE,
  stateAwards_FL,
  stateAwards_GA,
  stateAwards_GU,
  stateAwards_HI,
  stateAwards_IA,
  stateAwards_ID,
  stateAwards_IL,
  stateAwards_IN,
  stateAwards_KS,
  stateAwards_KY,
  stateAwards_LA,
  stateAwards_MA,
  stateAwards_MD,
  stateAwards_ME,
  stateAwards_MI,
  stateAwards_MN,
  stateAwards_MO,
  stateAwards_MS,
  stateAwards_MT,
  stateAwards_NC,
  stateAwards_ND,
  stateAwards_NE,
  stateAwards_NH,
  stateAwards_NJ,
  stateAwards_NM,
  stateAwards_NV,
  stateAwards_NY,
  stateAwards_OH,
  stateAwards_OK,
  stateAwards_OR,
  stateAwards_PA,
  stateAwards_PR,
  stateAwards_RI,
  stateAwards_SC,
  stateAwards_SD,
  stateAwards_TN,
  stateAwards_TX,
  stateAwards_UT,
  stateAwards_VA,
  stateAwards_VI,
  stateAwards_VT,
  stateAwards_WA,
  stateAwards_WI,
  stateAwards_WV,
  stateAwards_WY,
];

// stateCode set + state-name-to-code lookup, both derived from the files
// above (not hand-maintained) so DD214/NGB22 state-signal extraction
// elsewhere (musterCallProcessor.js) can validate against real data instead
// of a second, driftable list of US states/territories.
export const STATE_AWARD_CODES = new Set(
  STATE_AWARD_FILES.map((file) => file.stateCode),
);
export const STATE_NAME_TO_CODE = Object.fromEntries(
  STATE_AWARD_FILES.map((file) => [file.state.toUpperCase(), file.stateCode]),
);

// Helper function to get ribbon color by category
function getRibbonColorByCategory(category) {
  const categoryColors = {
    valor: "bg-gradient-to-r from-blue-600 via-white to-red-600",
    service: "bg-gradient-to-r from-green-600 via-yellow-400 to-green-600",
    campaign: "bg-gradient-to-r from-yellow-500 via-green-600 to-red-500",
    unit: "bg-gradient-to-r from-blue-500 via-red-500 to-blue-500",
    reserve: "bg-gradient-to-r from-yellow-400 via-blue-600 to-yellow-400",
    foreign: "bg-gradient-to-r from-red-600 via-white to-green-600",
    // Used by state/territory National Guard awards (category values
    // observed across all 54 stateAwards/*.json files: achievement, service,
    // unit, valor — the first 4 categories above already cover the other 3).
    achievement: "bg-gradient-to-r from-amber-500 via-yellow-200 to-amber-500",
  };
  return categoryColors[category] || "bg-gray-400";
}

// ============================================================================
// BRANCH PRECEDENCE REGULATIONS
// ============================================================================

export const PRECEDENCE_REGULATIONS = {
  Army: "AR 670-1",
  Navy: "NAVPERS 15665I",
  Marines: "MCO 1020.34H",
  "Air Force": "DAFI 36-2903",
  "Space Force": "DAFI 36-2903",
  "Coast Guard": "COMDTINST M1020.6K",
};

// ============================================================================
// ALIAS AUGMENTATIONS - abbreviations the scraped manifest doesn't list yet
// ============================================================================
// ribbon_manifest.json is regenerated by scripts/ribbon_scraper.py, so any
// alias edited directly in that file gets silently overwritten on the next
// scrape. Real DD214/NGB22 forms sometimes use abbreviations Wikipedia's
// award pages don't list (or list differently) — those extra aliases live
// here instead, keyed by manifest award id, and get merged in below.
const AWARD_ALIAS_AUGMENTATIONS = {
  // NGB/DD214 forms commonly abbreviate this "MFOM"; manifest only has "MFO".
  multinational_force_observers_medal: ["MFOM"],
  // This specific NGB22 form uses "NOPDR"; manifest only has "NCOPDR".
  nco_professional_development_ribbon: ["NOPDR"],
  // NGB22 forms commonly abbreviate these "GWOTS"/"GWOTE"; manifest only has
  // the longer "GWOTSM"/"GWOTEM" forms, which don't substring-match "GWOTS".
  global_war_on_terrorism_service_medal: ["GWOTS"],
  global_war_on_terrorism_expeditionary_medal: ["GWOTE"],
};

// Aliases the scraped manifest lists for one award but that are, in real
// DD214 usage, too ambiguous/generic to safely attribute to THAT award --
// removed here (keyed by manifest award id) rather than hand-edited in
// ribbon_manifest.json, which gets silently overwritten on the next scrape.
// The award's own full name (always tokenized, see _matchAward) and any
// remaining, unambiguous aliases still match normally.
const AWARD_ALIAS_REMOVALS = {
  // "NDSM" is the universal DD214/NGB22 abbreviation for the (near-
  // universal) National Defense Service Medal, not this senior valor award --
  // Navy DSM must require its full name or the unambiguous "NAVY DSM".
  navy_distinguished_service_medal: ["NDSM"],
  // A single common English word ("...ASSIGNED TO RECRUITING DUTY...")
  // fabricates this ribbon from unrelated remarks text; the full name and
  // "NRSR" abbreviation remain unambiguous.
  navy_recruiting_service_ribbon: ["RECRUITING"],
};

// ============================================================================
// STATE AWARDS - never part of the scraped federal-only manifest
// ============================================================================
// Sourced from src/data/stateAwards/{code}.json (54 files: 50 states + DC +
// PR + GU + VI), researched separately from the federal Wikipedia scrape.
// Each award already carries scope:"state"/stateCode/inStatePrecedence
// instead of the federal manifest's branch/precedence shape — parseDD214Text,
// sortRibbonsByPrecedence, and getAwardsForBranch below all branch on
// `award.scope === "state"` to handle the two shapes correctly.
const STATE_AWARD_ENTRIES = STATE_AWARD_FILES.flatMap((file) =>
  file.awards.map((award) => ({
    ...award,
    // The abbreviation is a real identifier from the sourced data (not
    // invented) -- folding it into aliases lets it participate in matching
    // the same way manifest aliases do. MIN_ALIAS_LENGTH below still filters
    // out 2-char abbreviations as OCR-noise-prone, same as federal awards.
    aliases: Array.from(
      new Set([
        ...(award.aliases || []),
        ...(award.abbreviation ? [award.abbreviation] : []),
      ]),
    ),
    assetFilename: null,
  })),
);

const _applyAliasAugmentation = (award) => {
  const removals = new Set(
    (AWARD_ALIAS_REMOVALS[award.id] || []).map((a) => a.toUpperCase()),
  );
  const baseAliases = award.aliases.filter(
    (alias) => !removals.has(alias.toUpperCase()),
  );
  return {
    ...award,
    aliases: [...baseAliases, ...(AWARD_ALIAS_AUGMENTATIONS[award.id] || [])],
  };
};

// ============================================================================
// MASTER AWARDS DATABASE - Loaded from scraped manifest
// ============================================================================

// Use manifest data if available, otherwise fall back to hardcoded list
export const MASTER_AWARDS =
  ribbonManifest?.awards?.length > 0
    ? [
        ...ribbonManifest.awards.map((award) => ({
          ..._applyAliasAugmentation(award),
          assetFilename: award.asset_filename,
          // Add fallback ribbon colors based on category
          ribbonColor: getRibbonColorByCategory(award.category),
        })),
        ...STATE_AWARD_ENTRIES.map((award) => ({
          ...award,
          ribbonColor: getRibbonColorByCategory(award.category),
        })),
      ]
    : [
        // VALOR AWARDS (Highest Precedence) - Fallback hardcoded list
        {
          id: "medal_of_honor",
          name: "Medal of Honor",
          aliases: ["MOH", "MEDAL OF HONOR", "CONGRESSIONAL MEDAL OF HONOR"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 1,
            Navy: 1,
            Marines: 1,
            "Air Force": 1,
            "Coast Guard": 1,
            "Space Force": 1,
          },
          category: "valor",
          ribbonColor: "bg-gradient-to-r from-sky-400 via-white to-sky-400",
        },
        {
          id: "distinguished_service_cross",
          name: "Distinguished Service Cross",
          aliases: ["DSC", "DIST SVC CROSS", "DISTINGUISHED SERVICE CROSS"],
          branch: ["Army"],
          precedence: { Army: 2 },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-white via-red-600 to-blue-600",
        },
        {
          id: "navy_cross",
          name: "Navy Cross",
          aliases: ["NC", "NAVY CROSS"],
          branch: ["Navy", "Marines", "Coast Guard"],
          precedence: { Navy: 2, Marines: 2, "Coast Guard": 2 },
          category: "valor",
          ribbonColor: "bg-gradient-to-r from-blue-800 via-white to-blue-800",
        },
        {
          id: "air_force_cross",
          name: "Air Force Cross",
          aliases: ["AFC", "AF CROSS", "AIR FORCE CROSS"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 2, "Space Force": 2 },
          category: "valor",
          ribbonColor: "bg-gradient-to-r from-blue-500 via-white to-blue-500",
        },
        {
          id: "silver_star",
          name: "Silver Star",
          aliases: ["SS", "SILVER STAR", "SLVR STR", "SSM"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 5,
            Navy: 5,
            Marines: 5,
            "Air Force": 5,
            "Coast Guard": 6,
            "Space Force": 5,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-red-600 via-white via-red-600 to-blue-600",
        },
        {
          id: "legion_of_merit",
          name: "Legion of Merit",
          aliases: ["LOM", "LM", "LEGION OF MERIT", "LEG OF MERIT"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 7,
            Navy: 7,
            Marines: 7,
            "Air Force": 7,
            "Coast Guard": 8,
            "Space Force": 7,
          },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-700 via-white to-red-700",
        },
        {
          id: "distinguished_flying_cross",
          name: "Distinguished Flying Cross",
          aliases: ["DFC", "DIST FLY CROSS", "DISTINGUISHED FLYING CROSS"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 8,
            Navy: 8,
            Marines: 8,
            "Air Force": 8,
            "Coast Guard": 9,
            "Space Force": 8,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-white via-red-500 to-blue-500",
        },
        {
          id: "bronze_star",
          name: "Bronze Star Medal",
          aliases: [
            "BSM",
            "BS",
            "BRONZE STAR",
            "BRNZ STR",
            "BRONZE STAR MEDAL",
            "BSM W/V",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 10,
            Navy: 10,
            Marines: 10,
            "Air Force": 10,
            "Coast Guard": 11,
            "Space Force": 10,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-white via-blue-600 via-white to-red-600",
        },
        {
          id: "purple_heart",
          name: "Purple Heart",
          aliases: ["PH", "PURPLE HEART", "PRPL HRT"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 11,
            Navy: 11,
            Marines: 11,
            "Air Force": 11,
            "Coast Guard": 12,
            "Space Force": 11,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-purple-700 via-white to-purple-700",
        },
        {
          id: "meritorious_service_medal",
          name: "Meritorious Service Medal",
          aliases: ["MSM", "MRT SVC MDL", "MERITORIOUS SERVICE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 13,
            Navy: 13,
            Marines: 13,
            "Air Force": 13,
            "Coast Guard": 14,
            "Space Force": 13,
          },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-700 via-white to-red-700",
        },
        {
          id: "air_medal",
          name: "Air Medal",
          aliases: ["AM", "AIR MEDAL", "AIR MDL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 14,
            Navy: 14,
            Marines: 14,
            "Air Force": 14,
            "Coast Guard": 15,
            "Space Force": 14,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-orange-400 to-blue-500",
        },
        {
          id: "army_commendation_medal",
          name: "Army Commendation Medal",
          aliases: ["ARCOM", "ACM", "ARMY COM MDL", "ARMY COMMENDATION MEDAL"],
          branch: ["Army"],
          precedence: { Army: 16 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-green-600 via-white to-green-600",
        },
        {
          id: "navy_marine_corps_commendation_medal",
          name: "Navy and Marine Corps Commendation Medal",
          aliases: [
            "NMCCM",
            "NAV COM MDL",
            "NAVY COMMENDATION MEDAL",
            "NAVY COM",
          ],
          branch: ["Navy", "Marines", "Coast Guard"],
          precedence: { Navy: 16, Marines: 16, "Coast Guard": 17 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-green-600 via-white to-green-600",
        },
        {
          id: "air_force_commendation_medal",
          name: "Air Force Commendation Medal",
          aliases: ["AFCM", "AF COM MDL", "AIR FORCE COMMENDATION MEDAL"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 16, "Space Force": 16 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-yellow-400 to-blue-500",
        },
        {
          id: "army_achievement_medal",
          name: "Army Achievement Medal",
          aliases: ["AAM", "ARMY ACH MDL", "ARMY ACHIEVEMENT MEDAL"],
          branch: ["Army"],
          precedence: { Army: 18 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-green-500 via-white to-green-500",
        },
        {
          id: "navy_marine_corps_achievement_medal",
          name: "Navy and Marine Corps Achievement Medal",
          aliases: [
            "NMCAM",
            "NAV ACH MDL",
            "NAVY ACHIEVEMENT MEDAL",
            "NAVY ACH",
          ],
          branch: ["Navy", "Marines"],
          precedence: { Navy: 18, Marines: 18 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-green-500 via-orange-400 to-green-500",
        },
        {
          id: "air_force_achievement_medal",
          name: "Air Force Achievement Medal",
          aliases: ["AFAM", "AF ACH MDL", "AIR FORCE ACHIEVEMENT MEDAL"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 18, "Space Force": 18 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-400 via-yellow-300 to-blue-400",
        },
        {
          id: "combat_action_ribbon",
          name: "Combat Action Ribbon",
          aliases: ["CAR", "COMBAT ACTION RIBBON"],
          branch: ["Navy", "Marines", "Coast Guard"],
          precedence: { Navy: 19, Marines: 19, "Coast Guard": 21 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-yellow-400 via-red-500 to-blue-600",
        },
        {
          id: "good_conduct_medal_army",
          name: "Good Conduct Medal (Army)",
          aliases: ["GCM", "GOOD CONDUCT MEDAL", "ARMY GCM"],
          branch: ["Army"],
          precedence: { Army: 31 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-white via-blue-600 to-red-600",
        },
        {
          id: "good_conduct_medal_navy",
          name: "Good Conduct Medal (Navy)",
          aliases: ["GCM", "NAVY GCM"],
          branch: ["Navy"],
          precedence: { Navy: 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-700 via-blue-800 to-red-700",
        },
        {
          id: "good_conduct_medal_marine",
          name: "Good Conduct Medal (Marine Corps)",
          aliases: ["GCM", "MARINE GCM"],
          branch: ["Marines"],
          precedence: { Marines: 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-600 via-white to-red-600",
        },
        {
          id: "good_conduct_medal_air_force",
          name: "Good Conduct Medal (Air Force)",
          aliases: ["GCM", "AF GCM"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 31, "Space Force": 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-blue-500 via-red-500 to-blue-500",
        },
        {
          id: "good_conduct_medal_coast_guard",
          name: "Good Conduct Medal (Coast Guard)",
          aliases: ["GCM", "CG GCM"],
          branch: ["Coast Guard"],
          precedence: { "Coast Guard": 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-600 via-white to-red-600",
        },
        {
          id: "national_defense_service_medal",
          name: "National Defense Service Medal",
          aliases: [
            "NDSM",
            "NAT DEF SVC MDL",
            "NATIONAL DEFENSE SERVICE MEDAL",
            "NAT DEF",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 40,
            Navy: 40,
            Marines: 40,
            "Air Force": 40,
            "Coast Guard": 40,
            "Space Force": 40,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-yellow-400 to-red-600",
        },
        {
          id: "afghanistan_campaign_medal",
          name: "Afghanistan Campaign Medal",
          aliases: [
            "ACM",
            "AFGHAN CAMP MDL",
            "AFGHANISTAN CAMPAIGN MEDAL",
            "OEF",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 41,
            Navy: 41,
            Marines: 41,
            "Air Force": 41,
            "Coast Guard": 41,
            "Space Force": 41,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-green-700 via-yellow-500 to-red-600",
        },
        {
          id: "iraq_campaign_medal",
          name: "Iraq Campaign Medal",
          aliases: [
            "ICM",
            "IRAQ CAMP MDL",
            "IRAQ CAMPAIGN MEDAL",
            "OIF",
            "OND",
            "OIR",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 42,
            Navy: 42,
            Marines: 42,
            "Air Force": 42,
            "Coast Guard": 42,
            "Space Force": 42,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-yellow-400 to-green-600",
        },
        {
          id: "global_war_on_terrorism_expeditionary_medal",
          name: "Global War on Terrorism Expeditionary Medal",
          aliases: ["GWOTEM", "GWOT EXP", "GWOT EXPEDITIONARY"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 44,
            Navy: 44,
            Marines: 44,
            "Air Force": 44,
            "Coast Guard": 44,
            "Space Force": 44,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-yellow-400 via-blue-600 to-red-600",
        },
        {
          id: "global_war_on_terrorism_service_medal",
          name: "Global War on Terrorism Service Medal",
          aliases: ["GWOTSM", "GWOT SVC", "GWOT SERVICE"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 45,
            Navy: 45,
            Marines: 45,
            "Air Force": 45,
            "Coast Guard": 45,
            "Space Force": 45,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-red-500 via-white via-blue-500 to-red-500",
        },
        {
          id: "armed_forces_expeditionary_medal",
          name: "Armed Forces Expeditionary Medal",
          aliases: ["AFEM", "ARMED FORCES EXP", "AFE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 47,
            Navy: 47,
            Marines: 47,
            "Air Force": 47,
            "Coast Guard": 47,
            "Space Force": 47,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-yellow-400 to-blue-500",
        },
        {
          id: "armed_forces_service_medal",
          name: "Armed Forces Service Medal",
          aliases: ["AFSM", "ARMED FORCES SVC", "AFS MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 48,
            Navy: 48,
            Marines: 48,
            "Air Force": 48,
            "Coast Guard": 48,
            "Space Force": 48,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-yellow-300 to-blue-600",
        },
        {
          id: "humanitarian_service_medal",
          name: "Humanitarian Service Medal",
          aliases: ["HSM", "HUMANITARIAN SVC", "HUMANITARIAN SERVICE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 49,
            Navy: 49,
            Marines: 49,
            "Air Force": 49,
            "Coast Guard": 49,
            "Space Force": 49,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-purple-600 via-white to-purple-600",
        },
        {
          id: "armed_forces_reserve_medal",
          name: "Armed Forces Reserve Medal",
          aliases: ["AFRM", "AF RESERVE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 55,
            Navy: 55,
            Marines: 55,
            "Air Force": 55,
            "Coast Guard": 55,
            "Space Force": 55,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-yellow-400 via-blue-600 to-yellow-400",
        },
        {
          id: "army_service_ribbon",
          name: "Army Service Ribbon",
          aliases: ["ASR", "ARMY SVC RIBBON"],
          branch: ["Army"],
          precedence: { Army: 57 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-green-600 via-yellow-400 to-green-600",
        },
        {
          id: "overseas_service_ribbon_army",
          name: "Overseas Service Ribbon (Army)",
          aliases: ["OSR", "ARMY OVERSEAS"],
          branch: ["Army"],
          precedence: { Army: 58 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-white via-blue-600 to-red-600",
        },
        {
          id: "nato_medal",
          name: "NATO Medal",
          aliases: ["NATO", "NATO MEDAL", "NATO SVC"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 70,
            Navy: 70,
            Marines: 70,
            "Air Force": 70,
            "Coast Guard": 70,
            "Space Force": 70,
          },
          category: "foreign",
          ribbonColor: "bg-gradient-to-r from-blue-700 via-white to-blue-700",
        },
        ...STATE_AWARD_ENTRIES.map((award) => ({
          ...award,
          ribbonColor: getRibbonColorByCategory(award.category),
        })),
      ];

// ============================================================================
// DEVICE DEFINITIONS
// ============================================================================

export const DEVICES = {
  bronze_star: {
    name: "Bronze Service Star",
    color: "#CD7F32",
    symbol: "★",
    size: "sm",
  },
  silver_star: {
    name: "Silver Service Star",
    color: "#C0C0C0",
    symbol: "★",
    size: "sm",
  },
  gold_star: {
    name: "Gold Service Star",
    color: "#FFD700",
    symbol: "★",
    size: "sm",
  },
  bronze_olc: {
    name: "Bronze Oak Leaf Cluster",
    color: "#CD7F32",
    symbol: "🌿",
    size: "sm",
  },
  silver_olc: {
    name: "Silver Oak Leaf Cluster",
    color: "#C0C0C0",
    symbol: "🌿",
    size: "sm",
  },
  v_device: {
    name: "V Device (Valor)",
    color: "#CD7F32",
    symbol: "V",
    size: "sm",
  },
  c_device: {
    name: "C Device (Combat)",
    color: "#CD7F32",
    symbol: "C",
    size: "sm",
  },
  r_device: {
    name: "R Device (Remote)",
    color: "#CD7F32",
    symbol: "R",
    size: "sm",
  },
  m_device: {
    name: "M Device (Mobilization)",
    color: "#CD7F32",
    symbol: "M",
    size: "sm",
  },
  arrowhead: { name: "Arrowhead", color: "#CD7F32", symbol: "▲", size: "sm" },
  numeral: { name: "Numeral", color: "#CD7F32", symbol: "#", size: "sm" },
};

// ============================================================================
// DD214 PARSING
// ============================================================================

// Every place `token` occurs in `text` as its own token rather than merely as
// a substring of a longer alphanumeric run. Plain `.includes()` alias matching
// false-positives badly on compact "//"-delimited abbreviation formats (e.g.
// NGB22 Block 15: "NDSM//ASR//AAM-2//..."), where short aliases like "SM"
// (Soldier's Medal) or "AM" (Air Medal) are substrings of unrelated
// neighboring tokens ("NDSM", "AAM-2") and would otherwise be reported as
// awards the veteran never received. Sentence-style Block 13 text (aliases
// already separated by spaces/punctuation) is unaffected by this check.
function _boundaryOccurrences(text, token) {
  const isAlnum = (ch) => /[A-Z0-9]/.test(ch);
  const occurrences = [];
  let idx = text.indexOf(token);
  while (idx !== -1) {
    const before = idx === 0 ? "" : text[idx - 1];
    const afterIdx = idx + token.length;
    const after = afterIdx >= text.length ? "" : text[afterIdx];
    if (!isAlnum(before) && !isAlnum(after)) {
      occurrences.push({ start: idx, end: afterIdx });
    }
    idx = text.indexOf(token, idx + 1);
  }
  return occurrences;
}

// Two-character aliases ("LM" Legion of Merit, "SM" Soldier's Medal, "PH",
// "SS", "BS", "AM", "NC") are not distinctive enough to match on even with the
// word-boundary check above: OCR of a degraded DD214 scan emits standalone
// two-letter noise tokens (a garbled "13. DECORATIONS ... BADGES" form label
// came out as "AWAR LM ST DAS"), which are legitimately boundary-delimited and
// would fabricate exactly the high-value valor awards a veteran never
// received. Every award carrying a two-char alias also carries its full name
// and/or a 3+ character abbreviation.
const MIN_ALIAS_LENGTH = 3;

// Find EVERY place a single award's name or any of its aliases matches in
// normalizedText, returning all matched spans. Every occurrence matters, not
// just the first: the same federal award name can appear both nested inside a
// longer state award name ("TEXAS MEDAL OF HONOR") and standalone elsewhere in
// the same document, and a first-occurrence-only model would suppress the
// award on the strength of the nested occurrence and silently drop a real
// award the veteran holds. `matchedAlias` keeps its original meaning -- the
// award's own name if that matched, else the first matching alias -- because
// extractContext/detectDevices/detectQuantity search on it. It is uppercased
// (unlike the manifest's own mixed case) so it stays indexOf-locatable in
// normalizedText -- the researched state-award aliases are natural/title case
// ("Texas Medal of Honor"), so comparing them raw would silently never match.
function _matchAward(normalizedText, award) {
  const tokens = [award.name.toUpperCase()];
  for (const alias of award.aliases) {
    const upperAlias = alias.toUpperCase();
    if (upperAlias.length >= MIN_ALIAS_LENGTH) {
      tokens.push(upperAlias);
    }
  }

  let matchedAlias = "";
  const spans = [];
  for (const token of tokens) {
    const occurrences = _boundaryOccurrences(normalizedText, token);
    if (occurrences.length === 0) continue;
    if (!matchedAlias) matchedAlias = token;
    spans.push(...occurrences);
  }
  if (!matchedAlias) return null;

  return { award, matchedAlias, spans };
}

// Scan EVERY award in MASTER_AWARDS (no branch/stateCode eligibility gate)
// for a name/alias match, purely to know what the raw text actually
// contains. Used only as the reference set for nested-match suppression
// below -- an award found here is never reported on its own unless it also
// passes the real branch/stateCode eligibility gate (see
// parseDD214Text/_suppressNestedAwardMatches).
function _matchAllAwardSpans(normalizedText) {
  const processedIds = new Set();
  const spans = [];

  for (const award of MASTER_AWARDS) {
    if (processedIds.has(award.id)) continue;
    const hit = _matchAward(normalizedText, award);
    if (hit) {
      processedIds.add(award.id);
      spans.push(hit);
    }
  }

  return spans;
}

function _isEligibleAward(award, branch, stateCode) {
  if (award.scope === "state") {
    // State-scoped awards carry no `branch` array at all (see the state
    // JSON schema) and are only eligible when the caller resolved a
    // matching stateCode -- without one, only federal awards can match.
    return Boolean(stateCode) && award.stateCode === stateCode;
  }
  return award.branch.includes(branch);
}

// Longest-match-wins: MASTER_AWARDS merges 780 state awards on top of the 89
// federal ones, and many state award full names/abbreviations legitimately
// CONTAIN a federal award's full name/abbreviation as a substring (e.g.
// Texas's "Texas Medal of Honor" alias contains the federal "Medal of
// Honor"; Hawaii's "HSM" abbreviation is verbatim identical to the federal
// Humanitarian Service Medal's). Returns the Set of `candidates` entries (by
// reference) that should NOT be reported.
function _suppressNestedAwardMatches(candidates, allSpans) {
  const suppressed = new Set();

  for (const a of candidates) {
    // An award is only suppressed when EVERY one of its occurrences is
    // accounted for by a more specific reading. A single unexplained
    // occurrence means the veteran really does hold the award -- a document
    // listing both "TEXAS MEDAL OF HONOR" and a standalone "MEDAL OF HONOR",
    // or both "DEFENSE MERITORIOUS SERVICE MEDAL" and "MERITORIOUS SERVICE
    // MEDAL" (DD214 precedence order lists them exactly that way), must
    // report both awards.
    const everyOccurrenceExplained = a.spans.every((span) => {
      const spanLen = span.end - span.start;

      // Rule 1 (unambiguous from the text alone): some award's name/alias --
      // reportable to this veteran or not -- strictly longer and fully
      // containing this occurrence exists in the raw text. The text itself
      // proves this occurrence is the wrong (nested, less specific) read
      // regardless of whether the more specific award actually belongs to
      // this veteran -- a Texas-shaped collision must not resolve to the
      // federal award for an Oregon veteran, or for no state at all, either.
      const hasLongerContainer = allSpans.some(
        (b) =>
          b.award.id !== a.award.id &&
          b.spans.some(
            (bSpan) =>
              bSpan.start <= span.start &&
              span.end <= bSpan.end &&
              bSpan.end - bSpan.start > spanLen,
          ),
      );
      if (hasLongerContainer) return true;

      // Rule 2 (ambiguous, needs the veteran's own scope to resolve): an
      // EXACT-span tie, e.g. the "HSM" abbreviation shared verbatim by the
      // federal Humanitarian Service Medal and Hawaii's own -- abbreviations
      // are meant to be unambiguous, unlike full names, which can legitimately
      // nest. Only resolved in favor of the state award when that state award
      // is itself reportable to this veteran (their own resolved stateCode);
      // a bare abbreviation must not be reinterpreted as a different state's
      // award for a veteran who never claimed that state.
      return candidates.some(
        (b) =>
          b !== a &&
          b.award.scope === "state" &&
          a.award.scope !== "state" &&
          b.spans.some(
            (bSpan) =>
              bSpan.start === span.start && bSpan.end - bSpan.start === spanLen,
          ),
      );
    });

    if (everyOccurrenceExplained) {
      suppressed.add(a);
    }
  }

  return suppressed;
}

/**
 * Parse DD214 text to extract awards with devices
 * @param {string} rawText - Raw text from DD214 Block 13/18
 * @param {string} branch - Veteran's primary branch of service
 * @param {string} [stateCode] - Veteran's National Guard state/territory code.
 *   State-scoped awards (scope:"state") only match when this is provided and
 *   equals the award's own stateCode; omitting it preserves the exact prior
 *   behavior of matching federal awards only.
 * @returns {Array} Array of { awardId, devices: [], quantity: number }
 */
export function parseDD214Text(rawText, branch = "Army", stateCode = null) {
  if (!rawText || typeof rawText !== "string") {
    return [];
  }

  // ============================================================
  // DD214 FORM STRUCTURE:
  // 1. FIELD LABELS = BOLD ALL CAPS
  // 2. INSTRUCTIONS = (parenthetic, often lowercase/mixed case)
  //    These contain EXAMPLE awards like "Silver Star, Bronze Star..."
  // 3. ACTUAL DATA = ALL CAPS, not in parentheses
  //
  // Key: Remove parenthetical content and lowercase text!
  // ============================================================

  let cleanedText = rawText;

  // STEP 1: Remove ALL parenthetical content (instructions/examples)
  // Excludes "/" from the character class: real DD214/NGB22 award data is
  // always "//"-delimited (the form's own field separator), and a genuine
  // single instructional parenthetical never contains a literal "//" inside
  // it. Some real NGB22 OCR scans have an unclosed opening paren right
  // before the actual award list (the form's own instructional text runs on
  // without its own closing paren) — without this exclusion, the greedy
  // match spans across the "//"-delimited award tokens to the NEXT ")" in a
  // later, unrelated field and deletes the entire real award list.
  // eslint-disable-next-line sonarjs/slow-regex -- {0,300} bounds backtracking to O(300n); measured 9.1s -> 55ms at 100k unmatched "(" (the "linear-time" claim this replaced was wrong -- unanchored /g matching retries the full backtrack at every start position when ")" never appears)
  cleanedText = cleanedText.replace(/\([^)/]{0,300}\)/g, " ");

  // STEP 2: Remove instructional patterns
  const INSTRUCTIONAL_PATTERNS = [
    /SILVER\s+STAR.*?BRONZE\s+STAR.*?AIR\s+MEDAL/gi,
    // \b-anchored so "E.G."/"I.E." only match as standalone abbreviations,
    // not as substrings inside real award names ("LEGION OF MERIT",
    // "SOLDIER'S MEDAL", "ARMY ACHIEVEMENT MEDAL" all contain "EG"/"IE").
    /SUCH\s+AS|FOR\s+EXAMPLE|\bE\.?G\.?\b|\bI\.?E\.?\b/gi,
    /EXAMPLES?\s+(?:OF\s+)?(?:DECORATIONS|MEDALS|AWARDS)/gi,
    // Remove words with 3+ lowercase letters (instructions, not data)
    /[a-z]{3,}/g,
  ];

  for (const pattern of INSTRUCTIONAL_PATTERNS) {
    cleanedText = cleanedText.replace(pattern, " ");
  }

  // If the cleaned text is nearly empty, the input was likely all instructional
  if (cleanedText.trim().length < 20) {
    return [];
  }

  // Normalize text: uppercase, remove extra spaces
  const normalizedText = cleanedText
    .toUpperCase()
    .replace(/\s+/g, " ")
    .replace(/[,;]/g, " ")
    .trim();

  const allSpans = _matchAllAwardSpans(normalizedText);
  const candidates = allSpans.filter((span) =>
    _isEligibleAward(span.award, branch, stateCode),
  );
  const suppressed = _suppressNestedAwardMatches(candidates, allSpans);

  const foundAwards = [];
  for (const candidate of candidates) {
    if (suppressed.has(candidate)) continue;
    const { award, matchedAlias } = candidate;

    // Detect devices
    const devices = detectDevices(normalizedText, matchedAlias, branch);

    // Detect quantity (for oak leaf clusters or stars)
    const quantity = detectQuantity(normalizedText, matchedAlias);

    foundAwards.push({
      awardId: award.id,
      award: award,
      devices: devices,
      quantity: quantity,
      matchedText: matchedAlias,
    });
  }

  return foundAwards;
}

/**
 * Detect devices attached to an award
 */
function _addOakLeafClusters(devices, context) {
  // eslint-disable-next-line sonarjs/slow-regex -- simple digit+alternation, no overlapping ambiguity; context is a short extracted snippet, not attacker-controlled
  const olcMatch = context.match(/(\d+)\s*(OLC|OAK\s*LEAF)/);
  if (olcMatch) {
    const count = parseInt(olcMatch[1], 10);
    const silverOLC = Math.floor(count / 5);
    const bronzeOLC = count % 5;

    for (let i = 0; i < silverOLC; i++) {
      devices.push({ type: "silver_olc", position: i });
    }
    for (let i = 0; i < bronzeOLC; i++) {
      devices.push({ type: "bronze_olc", position: silverOLC + i });
    }
  } else if (/OLC|OAK\s*LEAF/.test(context)) {
    devices.push({ type: "bronze_olc", position: 0 });
  }
}

function _addServiceStars(devices, context) {
  // eslint-disable-next-line sonarjs/slow-regex -- simple digit+alternation, no overlapping ambiguity; context is a short extracted snippet, not attacker-controlled
  const starMatch = context.match(/(\d+)\s*(STAR|STR|\*)/);
  if (!starMatch) return;

  const count = parseInt(starMatch[1], 10);
  const goldStars = Math.floor(count / 25);
  const silverStars = Math.floor((count % 25) / 5);
  const bronzeStars = count % 5;

  for (let i = 0; i < goldStars; i++) {
    devices.push({ type: "gold_star", position: i });
  }
  for (let i = 0; i < silverStars; i++) {
    devices.push({ type: "silver_star", position: goldStars + i });
  }
  for (let i = 0; i < bronzeStars; i++) {
    devices.push({
      type: "bronze_star",
      position: goldStars + silverStars + i,
    });
  }
}

function detectDevices(text, awardMatch, branch) {
  const devices = [];
  const context = extractContext(text, awardMatch, 50);

  // V Device (Valor)
  if (/W\/?V|WITH\s*V|V\s*DEVICE|VALOR/.test(context)) {
    devices.push({ type: "v_device", position: "center" });
  }

  // C Device (Combat)
  if (/W\/?C|WITH\s*C|C\s*DEVICE|COMBAT\s*DIST/.test(context)) {
    devices.push({ type: "c_device", position: "center" });
  }

  // R Device (Remote)
  if (/W\/?R|WITH\s*R|R\s*DEVICE|REMOTE/.test(context)) {
    devices.push({ type: "r_device", position: "center" });
  }

  // M Device (Mobilization - e.g. Armed Forces Reserve Medal, Oregon NG
  // Faithful Service Ribbon). NOTE: the Armed Forces Reserve Medal's
  // traditional device is an Hourglass per additional qualifying period, not
  // a numeral count — this detector only recognizes the literal "M device"
  // token, it does not attempt to translate a trailing numeral (e.g. the
  // "-2" in "AFRM-W/M-DEV-2") into hourglass count vs. award number; that
  // ambiguity is left undecided rather than guessed at.
  if (/W\/?M|WITH\s*M|M\s*DEVICE|MOBILIZATION/.test(context)) {
    devices.push({ type: "m_device", position: "center" });
  }

  // Oak Leaf Clusters (Army/Air Force)
  if (branch === "Army" || branch === "Air Force" || branch === "Space Force") {
    _addOakLeafClusters(devices, context);
  }

  // Service Stars (Navy/Marines/Coast Guard)
  if (branch === "Navy" || branch === "Marines" || branch === "Coast Guard") {
    _addServiceStars(devices, context);
  }

  // Arrowhead device
  if (/ARROWHEAD|ARROW/.test(context)) {
    devices.push({ type: "arrowhead", position: 0 });
  }

  return devices;
}

/**
 * Extract text context around a match
 */
function extractContext(text, match, chars) {
  const index = text.indexOf(match);
  if (index === -1) return text;

  let start = Math.max(0, index - chars);
  let end = Math.min(text.length, index + match.length + chars);

  // NGB22/DD214 "Block 15"-style forms pack awards as "//"-delimited tokens
  // (e.g. "AFRM-W/M-DEV-2//CAB//NATO-MDL") with far less than `chars`
  // between neighboring awards. A flat character radius bleeds a
  // neighboring award's own device/quantity markers into this award's
  // context. When "//" delimiters are present, clip the window to the
  // nearest one on each side so detection stays scoped to this award's own
  // token; sentence-style Block 13 text (no "//") is unaffected.
  const lastDelimBefore = text.slice(start, index).lastIndexOf("//");
  if (lastDelimBefore !== -1) {
    start = start + lastDelimBefore + 2;
  }
  const firstDelimAfter = text.slice(index + match.length, end).indexOf("//");
  if (firstDelimAfter !== -1) {
    end = index + match.length + firstDelimAfter;
  }

  return text.substring(start, end);
}

/**
 * Detect quantity of awards
 */
function detectQuantity(text, awardMatch) {
  const context = extractContext(text, awardMatch, 30);

  // Look for patterns like "(2)", "x2", "2nd", etc.
  // eslint-disable-next-line sonarjs/slow-regex -- simple single-quantifier patterns, no overlapping ambiguity
  const patterns = [/\((\d+)\)/, /x(\d+)/i, /(\d+)(?:ST|ND|RD|TH)\s*AWARD/i];

  for (const pattern of patterns) {
    const match = context.match(pattern);
    if (match) {
      return parseInt(match[1], 10);
    }
  }

  return 1;
}

// ============================================================================
// PRECEDENCE SORTING
// ============================================================================

// Per AR 670-1 (and equivalent branch regs), state awards sit below every
// federal award on a real uniform regardless of the state's own internal
// ordering. Used by both sortRibbonsByPrecedence and getAwardsForBranch so
// the two stay consistent.
function _precedenceSortValue(award, branch) {
  if (award?.scope === "state") {
    // 100000+ unambiguously sorts after any federal precedence value (the
    // highest observed federal Army precedence in the scraped manifest is
    // 75); null inStatePrecedence entries (no order asserted per-state) sort
    // last within their own state group via Number.POSITIVE_INFINITY.
    return 100000 + (award.inStatePrecedence ?? Number.POSITIVE_INFINITY);
  }
  return award?.precedence?.[branch] ?? 999;
}

/**
 * Sort ribbons by branch-specific order of precedence
 * @param {Array} awards - Array of award objects from parseDD214Text
 * @param {string} branch - Branch of service
 * @returns {Array} Sorted awards
 */
export function sortRibbonsByPrecedence(awards, branch) {
  if (!awards || !Array.isArray(awards)) {
    return [];
  }

  return [...awards].sort(
    (a, b) =>
      _precedenceSortValue(a.award, branch) -
      _precedenceSortValue(b.award, branch),
  );
}

/**
 * Get an award by ID
 */
export function getAwardById(awardId) {
  return MASTER_AWARDS.find((a) => a.id === awardId) || null;
}

// Awards persisted via addAward() (veteranProfile.js) only carry
// veteran-specific fields (name, dateReceived, notes, isCombat, ...) — never
// the visual metadata (assetFilename, ribbonColor, category) that lives on
// the matching MASTER_AWARDS entry, because that entry's own `id` is a
// stable slug (e.g. "national_defense_service_medal") while a stored
// award's `id` is a random `award_${Date.now()}_...` string with no
// relationship to it. Matching must happen by normalized name instead.
// Custom awards a veteran typed in manually (no MASTER_AWARDS match) fall
// back to the award as stored, so the caller's existing gray/color-class
// fallback still applies instead of crashing or showing a broken image.
export function enrichAwardForDisplay(award) {
  if (!award) return award;
  const normalizedName = (award.name || "").trim().toLowerCase();
  const masterMatch = MASTER_AWARDS.find(
    (a) => (a.name || "").trim().toLowerCase() === normalizedName,
  );
  if (!masterMatch) return award;
  return { ...masterMatch, ...award };
}

/**
 * Get awards applicable to a specific branch
 * @param {string} branch - Branch of service
 * @param {string} [stateCode] - Veteran's National Guard state/territory
 *   code. State-scoped awards only appear when this matches their stateCode.
 */
export function getAwardsForBranch(branch, stateCode = null) {
  return MASTER_AWARDS.filter((a) =>
    a.scope === "state"
      ? !!stateCode && a.stateCode === stateCode
      : a.branch.includes(branch),
  ).sort(
    (a, b) => _precedenceSortValue(a, branch) - _precedenceSortValue(b, branch),
  );
}

// ============================================================================
// RACK LAYOUT CALCULATIONS
// ============================================================================

/**
 * Calculate ribbon rack layout
 * @param {Array} sortedAwards - Awards sorted by precedence
 * @param {number} ribbonsPerRow - Ribbons per row (3 or 4)
 * @returns {Array} Array of rows, each containing ribbon objects
 */
export function calculateRackLayout(sortedAwards, ribbonsPerRow = 3) {
  if (!sortedAwards || sortedAwards.length === 0) {
    return [];
  }

  const rows = [];
  const totalRibbons = sortedAwards.length;

  // Calculate how many full rows and remainder
  const _fullRows = Math.floor(totalRibbons / ribbonsPerRow);
  const remainder = totalRibbons % ribbonsPerRow;

  let index = 0;

  // Top row (may be partial - should be centered)
  if (remainder > 0) {
    const topRow = {
      ribbons: sortedAwards.slice(index, index + remainder),
      isPartial: true,
      count: remainder,
      alignment: "center",
    };
    rows.push(topRow);
    index += remainder;
  }

  // Full rows
  while (index < totalRibbons) {
    const row = {
      ribbons: sortedAwards.slice(index, index + ribbonsPerRow),
      isPartial: false,
      count: ribbonsPerRow,
      alignment: "full",
    };
    rows.push(row);
    index += ribbonsPerRow;
  }

  return rows;
}

// ============================================================================
// UTILITY EXPORTS
// ============================================================================

export default {
  MASTER_AWARDS,
  DEVICES,
  PRECEDENCE_REGULATIONS,
  parseDD214Text,
  sortRibbonsByPrecedence,
  getAwardById,
  getAwardsForBranch,
  calculateRackLayout,
};
