/**
 * Vet-Rate.org - Ribbon Rack Data Utilities
 * ==========================================
 *
 * DD214 Parser, Precedence Sorter, and Device Handler
 *
 * This module provides:
 * 1. parseDD214Text() - Extract awards from DD214 text
 * 2. sortRibbonsByPrecedence() - Sort by branch-specific order
 * 3. Device attachment logic for visual rendering
 */

// Import the scraped manifest (generated by ribbon_scraper.py)
import ribbonManifest from "../data/ribbon_manifest.json";

// Helper function to get ribbon color by category
function getRibbonColorByCategory(category) {
  const categoryColors = {
    valor: "bg-gradient-to-r from-blue-600 via-white to-red-600",
    service: "bg-gradient-to-r from-green-600 via-yellow-400 to-green-600",
    campaign: "bg-gradient-to-r from-yellow-500 via-green-600 to-red-500",
    unit: "bg-gradient-to-r from-blue-500 via-red-500 to-blue-500",
    reserve: "bg-gradient-to-r from-yellow-400 via-blue-600 to-yellow-400",
    foreign: "bg-gradient-to-r from-red-600 via-white to-green-600",
  };
  return categoryColors[category] || "bg-gray-400";
}

// ============================================================================
// BRANCH PRECEDENCE REGULATIONS
// ============================================================================

export const PRECEDENCE_REGULATIONS = {
  Army: "AR 670-1",
  Navy: "NAVPERS 15665I",
  Marines: "MCO 1020.34H",
  "Air Force": "DAFI 36-2903",
  "Space Force": "DAFI 36-2903",
  "Coast Guard": "COMDTINST M1020.6K",
};

// ============================================================================
// MASTER AWARDS DATABASE - Loaded from scraped manifest
// ============================================================================

// Use manifest data if available, otherwise fall back to hardcoded list
export const MASTER_AWARDS =
  ribbonManifest?.awards?.length > 0
    ? ribbonManifest.awards.map((award) => ({
        ...award,
        assetFilename: award.asset_filename,
        // Add fallback ribbon colors based on category
        ribbonColor: getRibbonColorByCategory(award.category),
      }))
    : [
        // VALOR AWARDS (Highest Precedence) - Fallback hardcoded list
        {
          id: "medal_of_honor",
          name: "Medal of Honor",
          aliases: ["MOH", "MEDAL OF HONOR", "CONGRESSIONAL MEDAL OF HONOR"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 1,
            Navy: 1,
            Marines: 1,
            "Air Force": 1,
            "Coast Guard": 1,
            "Space Force": 1,
          },
          category: "valor",
          ribbonColor: "bg-gradient-to-r from-sky-400 via-white to-sky-400",
        },
        {
          id: "distinguished_service_cross",
          name: "Distinguished Service Cross",
          aliases: ["DSC", "DIST SVC CROSS", "DISTINGUISHED SERVICE CROSS"],
          branch: ["Army"],
          precedence: { Army: 2 },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-white via-red-600 to-blue-600",
        },
        {
          id: "navy_cross",
          name: "Navy Cross",
          aliases: ["NC", "NAVY CROSS"],
          branch: ["Navy", "Marines", "Coast Guard"],
          precedence: { Navy: 2, Marines: 2, "Coast Guard": 2 },
          category: "valor",
          ribbonColor: "bg-gradient-to-r from-blue-800 via-white to-blue-800",
        },
        {
          id: "air_force_cross",
          name: "Air Force Cross",
          aliases: ["AFC", "AF CROSS", "AIR FORCE CROSS"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 2, "Space Force": 2 },
          category: "valor",
          ribbonColor: "bg-gradient-to-r from-blue-500 via-white to-blue-500",
        },
        {
          id: "silver_star",
          name: "Silver Star",
          aliases: ["SS", "SILVER STAR", "SLVR STR", "SSM"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 5,
            Navy: 5,
            Marines: 5,
            "Air Force": 5,
            "Coast Guard": 6,
            "Space Force": 5,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-red-600 via-white via-red-600 to-blue-600",
        },
        {
          id: "legion_of_merit",
          name: "Legion of Merit",
          aliases: ["LOM", "LM", "LEGION OF MERIT", "LEG OF MERIT"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 7,
            Navy: 7,
            Marines: 7,
            "Air Force": 7,
            "Coast Guard": 8,
            "Space Force": 7,
          },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-700 via-white to-red-700",
        },
        {
          id: "distinguished_flying_cross",
          name: "Distinguished Flying Cross",
          aliases: ["DFC", "DIST FLY CROSS", "DISTINGUISHED FLYING CROSS"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 8,
            Navy: 8,
            Marines: 8,
            "Air Force": 8,
            "Coast Guard": 9,
            "Space Force": 8,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-white via-red-500 to-blue-500",
        },
        {
          id: "bronze_star",
          name: "Bronze Star Medal",
          aliases: [
            "BSM",
            "BS",
            "BRONZE STAR",
            "BRNZ STR",
            "BRONZE STAR MEDAL",
            "BSM W/V",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 10,
            Navy: 10,
            Marines: 10,
            "Air Force": 10,
            "Coast Guard": 11,
            "Space Force": 10,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-white via-blue-600 via-white to-red-600",
        },
        {
          id: "purple_heart",
          name: "Purple Heart",
          aliases: ["PH", "PURPLE HEART", "PRPL HRT"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 11,
            Navy: 11,
            Marines: 11,
            "Air Force": 11,
            "Coast Guard": 12,
            "Space Force": 11,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-purple-700 via-white to-purple-700",
        },
        {
          id: "meritorious_service_medal",
          name: "Meritorious Service Medal",
          aliases: ["MSM", "MRT SVC MDL", "MERITORIOUS SERVICE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 13,
            Navy: 13,
            Marines: 13,
            "Air Force": 13,
            "Coast Guard": 14,
            "Space Force": 13,
          },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-700 via-white to-red-700",
        },
        {
          id: "air_medal",
          name: "Air Medal",
          aliases: ["AM", "AIR MEDAL", "AIR MDL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 14,
            Navy: 14,
            Marines: 14,
            "Air Force": 14,
            "Coast Guard": 15,
            "Space Force": 14,
          },
          category: "valor",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-orange-400 to-blue-500",
        },
        {
          id: "army_commendation_medal",
          name: "Army Commendation Medal",
          aliases: ["ARCOM", "ACM", "ARMY COM MDL", "ARMY COMMENDATION MEDAL"],
          branch: ["Army"],
          precedence: { Army: 16 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-green-600 via-white to-green-600",
        },
        {
          id: "navy_marine_corps_commendation_medal",
          name: "Navy and Marine Corps Commendation Medal",
          aliases: [
            "NMCCM",
            "NAV COM MDL",
            "NAVY COMMENDATION MEDAL",
            "NAVY COM",
          ],
          branch: ["Navy", "Marines", "Coast Guard"],
          precedence: { Navy: 16, Marines: 16, "Coast Guard": 17 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-green-600 via-white to-green-600",
        },
        {
          id: "air_force_commendation_medal",
          name: "Air Force Commendation Medal",
          aliases: ["AFCM", "AF COM MDL", "AIR FORCE COMMENDATION MEDAL"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 16, "Space Force": 16 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-yellow-400 to-blue-500",
        },
        {
          id: "army_achievement_medal",
          name: "Army Achievement Medal",
          aliases: ["AAM", "ARMY ACH MDL", "ARMY ACHIEVEMENT MEDAL"],
          branch: ["Army"],
          precedence: { Army: 18 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-green-500 via-white to-green-500",
        },
        {
          id: "navy_marine_corps_achievement_medal",
          name: "Navy and Marine Corps Achievement Medal",
          aliases: [
            "NMCAM",
            "NAV ACH MDL",
            "NAVY ACHIEVEMENT MEDAL",
            "NAVY ACH",
          ],
          branch: ["Navy", "Marines"],
          precedence: { Navy: 18, Marines: 18 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-green-500 via-orange-400 to-green-500",
        },
        {
          id: "air_force_achievement_medal",
          name: "Air Force Achievement Medal",
          aliases: ["AFAM", "AF ACH MDL", "AIR FORCE ACHIEVEMENT MEDAL"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 18, "Space Force": 18 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-400 via-yellow-300 to-blue-400",
        },
        {
          id: "combat_action_ribbon",
          name: "Combat Action Ribbon",
          aliases: ["CAR", "COMBAT ACTION RIBBON"],
          branch: ["Navy", "Marines", "Coast Guard"],
          precedence: { Navy: 19, Marines: 19, "Coast Guard": 21 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-yellow-400 via-red-500 to-blue-600",
        },
        {
          id: "good_conduct_medal_army",
          name: "Good Conduct Medal (Army)",
          aliases: ["GCM", "GOOD CONDUCT MEDAL", "ARMY GCM"],
          branch: ["Army"],
          precedence: { Army: 31 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-white via-blue-600 to-red-600",
        },
        {
          id: "good_conduct_medal_navy",
          name: "Good Conduct Medal (Navy)",
          aliases: ["GCM", "NAVY GCM"],
          branch: ["Navy"],
          precedence: { Navy: 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-700 via-blue-800 to-red-700",
        },
        {
          id: "good_conduct_medal_marine",
          name: "Good Conduct Medal (Marine Corps)",
          aliases: ["GCM", "MARINE GCM"],
          branch: ["Marines"],
          precedence: { Marines: 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-600 via-white to-red-600",
        },
        {
          id: "good_conduct_medal_air_force",
          name: "Good Conduct Medal (Air Force)",
          aliases: ["GCM", "AF GCM"],
          branch: ["Air Force", "Space Force"],
          precedence: { "Air Force": 31, "Space Force": 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-blue-500 via-red-500 to-blue-500",
        },
        {
          id: "good_conduct_medal_coast_guard",
          name: "Good Conduct Medal (Coast Guard)",
          aliases: ["GCM", "CG GCM"],
          branch: ["Coast Guard"],
          precedence: { "Coast Guard": 31 },
          category: "service",
          ribbonColor: "bg-gradient-to-r from-red-600 via-white to-red-600",
        },
        {
          id: "national_defense_service_medal",
          name: "National Defense Service Medal",
          aliases: [
            "NDSM",
            "NAT DEF SVC MDL",
            "NATIONAL DEFENSE SERVICE MEDAL",
            "NAT DEF",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 40,
            Navy: 40,
            Marines: 40,
            "Air Force": 40,
            "Coast Guard": 40,
            "Space Force": 40,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-yellow-400 to-red-600",
        },
        {
          id: "afghanistan_campaign_medal",
          name: "Afghanistan Campaign Medal",
          aliases: [
            "ACM",
            "AFGHAN CAMP MDL",
            "AFGHANISTAN CAMPAIGN MEDAL",
            "OEF",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 41,
            Navy: 41,
            Marines: 41,
            "Air Force": 41,
            "Coast Guard": 41,
            "Space Force": 41,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-green-700 via-yellow-500 to-red-600",
        },
        {
          id: "iraq_campaign_medal",
          name: "Iraq Campaign Medal",
          aliases: [
            "ICM",
            "IRAQ CAMP MDL",
            "IRAQ CAMPAIGN MEDAL",
            "OIF",
            "OND",
            "OIR",
          ],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 42,
            Navy: 42,
            Marines: 42,
            "Air Force": 42,
            "Coast Guard": 42,
            "Space Force": 42,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-yellow-400 to-green-600",
        },
        {
          id: "global_war_on_terrorism_expeditionary_medal",
          name: "Global War on Terrorism Expeditionary Medal",
          aliases: ["GWOTEM", "GWOT EXP", "GWOT EXPEDITIONARY"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 44,
            Navy: 44,
            Marines: 44,
            "Air Force": 44,
            "Coast Guard": 44,
            "Space Force": 44,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-yellow-400 via-blue-600 to-red-600",
        },
        {
          id: "global_war_on_terrorism_service_medal",
          name: "Global War on Terrorism Service Medal",
          aliases: ["GWOTSM", "GWOT SVC", "GWOT SERVICE"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 45,
            Navy: 45,
            Marines: 45,
            "Air Force": 45,
            "Coast Guard": 45,
            "Space Force": 45,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-red-500 via-white via-blue-500 to-red-500",
        },
        {
          id: "armed_forces_expeditionary_medal",
          name: "Armed Forces Expeditionary Medal",
          aliases: ["AFEM", "ARMED FORCES EXP", "AFE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 47,
            Navy: 47,
            Marines: 47,
            "Air Force": 47,
            "Coast Guard": 47,
            "Space Force": 47,
          },
          category: "campaign",
          ribbonColor:
            "bg-gradient-to-r from-blue-500 via-yellow-400 to-blue-500",
        },
        {
          id: "armed_forces_service_medal",
          name: "Armed Forces Service Medal",
          aliases: ["AFSM", "ARMED FORCES SVC", "AFS MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 48,
            Navy: 48,
            Marines: 48,
            "Air Force": 48,
            "Coast Guard": 48,
            "Space Force": 48,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-blue-600 via-yellow-300 to-blue-600",
        },
        {
          id: "humanitarian_service_medal",
          name: "Humanitarian Service Medal",
          aliases: ["HSM", "HUMANITARIAN SVC", "HUMANITARIAN SERVICE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 49,
            Navy: 49,
            Marines: 49,
            "Air Force": 49,
            "Coast Guard": 49,
            "Space Force": 49,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-purple-600 via-white to-purple-600",
        },
        {
          id: "armed_forces_reserve_medal",
          name: "Armed Forces Reserve Medal",
          aliases: ["AFRM", "AF RESERVE MEDAL"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 55,
            Navy: 55,
            Marines: 55,
            "Air Force": 55,
            "Coast Guard": 55,
            "Space Force": 55,
          },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-yellow-400 via-blue-600 to-yellow-400",
        },
        {
          id: "army_service_ribbon",
          name: "Army Service Ribbon",
          aliases: ["ASR", "ARMY SVC RIBBON"],
          branch: ["Army"],
          precedence: { Army: 57 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-green-600 via-yellow-400 to-green-600",
        },
        {
          id: "overseas_service_ribbon_army",
          name: "Overseas Service Ribbon (Army)",
          aliases: ["OSR", "ARMY OVERSEAS"],
          branch: ["Army"],
          precedence: { Army: 58 },
          category: "service",
          ribbonColor:
            "bg-gradient-to-r from-red-600 via-white via-blue-600 to-red-600",
        },
        {
          id: "nato_medal",
          name: "NATO Medal",
          aliases: ["NATO", "NATO MEDAL", "NATO SVC"],
          branch: [
            "Army",
            "Navy",
            "Marines",
            "Air Force",
            "Coast Guard",
            "Space Force",
          ],
          precedence: {
            Army: 70,
            Navy: 70,
            Marines: 70,
            "Air Force": 70,
            "Coast Guard": 70,
            "Space Force": 70,
          },
          category: "foreign",
          ribbonColor: "bg-gradient-to-r from-blue-700 via-white to-blue-700",
        },
      ];

// ============================================================================
// DEVICE DEFINITIONS
// ============================================================================

export const DEVICES = {
  bronze_star: {
    name: "Bronze Service Star",
    color: "#CD7F32",
    symbol: "★",
    size: "sm",
  },
  silver_star: {
    name: "Silver Service Star",
    color: "#C0C0C0",
    symbol: "★",
    size: "sm",
  },
  gold_star: {
    name: "Gold Service Star",
    color: "#FFD700",
    symbol: "★",
    size: "sm",
  },
  bronze_olc: {
    name: "Bronze Oak Leaf Cluster",
    color: "#CD7F32",
    symbol: "🌿",
    size: "sm",
  },
  silver_olc: {
    name: "Silver Oak Leaf Cluster",
    color: "#C0C0C0",
    symbol: "🌿",
    size: "sm",
  },
  v_device: {
    name: "V Device (Valor)",
    color: "#CD7F32",
    symbol: "V",
    size: "sm",
  },
  c_device: {
    name: "C Device (Combat)",
    color: "#CD7F32",
    symbol: "C",
    size: "sm",
  },
  r_device: {
    name: "R Device (Remote)",
    color: "#CD7F32",
    symbol: "R",
    size: "sm",
  },
  arrowhead: { name: "Arrowhead", color: "#CD7F32", symbol: "▲", size: "sm" },
  numeral: { name: "Numeral", color: "#CD7F32", symbol: "#", size: "sm" },
};

// ============================================================================
// DD214 PARSING
// ============================================================================

/**
 * Parse DD214 text to extract awards with devices
 * @param {string} rawText - Raw text from DD214 Block 13/18
 * @param {string} branch - Veteran's primary branch of service
 * @returns {Array} Array of { awardId, devices: [], quantity: number }
 */
export function parseDD214Text(rawText, branch = "Army") {
  if (!rawText || typeof rawText !== "string") {
    return [];
  }

  // ============================================================
  // DD214 FORM STRUCTURE:
  // 1. FIELD LABELS = BOLD ALL CAPS
  // 2. INSTRUCTIONS = (parenthetic, often lowercase/mixed case)
  //    These contain EXAMPLE awards like "Silver Star, Bronze Star..."
  // 3. ACTUAL DATA = ALL CAPS, not in parentheses
  //
  // Key: Remove parenthetical content and lowercase text!
  // ============================================================

  let cleanedText = rawText;

  // STEP 1: Remove ALL parenthetical content (instructions/examples)
  cleanedText = cleanedText.replace(/\([^)]*\)/g, " ");

  // STEP 2: Remove instructional patterns
  const INSTRUCTIONAL_PATTERNS = [
    /SILVER\s+STAR.*?BRONZE\s+STAR.*?AIR\s+MEDAL/gi,
    /SUCH\s+AS|FOR\s+EXAMPLE|E\.?G\.?|I\.?E\.?/gi,
    /EXAMPLES?\s+(?:OF\s+)?(?:DECORATIONS|MEDALS|AWARDS)/gi,
    // Remove words with 3+ lowercase letters (instructions, not data)
    /[a-z]{3,}/g,
  ];

  for (const pattern of INSTRUCTIONAL_PATTERNS) {
    cleanedText = cleanedText.replace(pattern, " ");
  }

  // If the cleaned text is nearly empty, the input was likely all instructional
  if (cleanedText.trim().length < 20) {
    return [];
  }

  // Normalize text: uppercase, remove extra spaces
  const normalizedText = cleanedText
    .toUpperCase()
    .replace(/\s+/g, " ")
    .replace(/[,;]/g, " ")
    .trim();

  const foundAwards = [];
  const processedIds = new Set();

  // Check each award against the text
  for (const award of MASTER_AWARDS) {
    // Skip awards not applicable to this branch
    if (!award.branch.includes(branch)) {
      continue;
    }

    let matched = false;
    let matchedAlias = "";

    // Check main name
    if (normalizedText.includes(award.name.toUpperCase())) {
      matched = true;
      matchedAlias = award.name;
    }

    // Check aliases
    if (!matched) {
      for (const alias of award.aliases) {
        if (normalizedText.includes(alias)) {
          matched = true;
          matchedAlias = alias;
          break;
        }
      }
    }

    if (matched && !processedIds.has(award.id)) {
      processedIds.add(award.id);

      // Detect devices
      const devices = detectDevices(normalizedText, matchedAlias, branch);

      // Detect quantity (for oak leaf clusters or stars)
      const quantity = detectQuantity(normalizedText, matchedAlias);

      foundAwards.push({
        awardId: award.id,
        award: award,
        devices: devices,
        quantity: quantity,
        matchedText: matchedAlias,
      });
    }
  }

  return foundAwards;
}

/**
 * Detect devices attached to an award
 */
function detectDevices(text, awardMatch, branch) {
  const devices = [];
  const context = extractContext(text, awardMatch, 50);

  // V Device (Valor)
  if (/W\/?V|WITH\s*V|V\s*DEVICE|VALOR/.test(context)) {
    devices.push({ type: "v_device", position: "center" });
  }

  // C Device (Combat)
  if (/W\/?C|WITH\s*C|C\s*DEVICE|COMBAT\s*DIST/.test(context)) {
    devices.push({ type: "c_device", position: "center" });
  }

  // R Device (Remote)
  if (/W\/?R|WITH\s*R|R\s*DEVICE|REMOTE/.test(context)) {
    devices.push({ type: "r_device", position: "center" });
  }

  // Oak Leaf Clusters (Army/Air Force)
  if (branch === "Army" || branch === "Air Force" || branch === "Space Force") {
    const olcMatch = context.match(/(\d+)\s*(OLC|OAK\s*LEAF)/);
    if (olcMatch) {
      const count = parseInt(olcMatch[1], 10);
      const silverOLC = Math.floor(count / 5);
      const bronzeOLC = count % 5;

      for (let i = 0; i < silverOLC; i++) {
        devices.push({ type: "silver_olc", position: i });
      }
      for (let i = 0; i < bronzeOLC; i++) {
        devices.push({ type: "bronze_olc", position: silverOLC + i });
      }
    } else if (/OLC|OAK\s*LEAF/.test(context)) {
      devices.push({ type: "bronze_olc", position: 0 });
    }
  }

  // Service Stars (Navy/Marines/Coast Guard)
  if (branch === "Navy" || branch === "Marines" || branch === "Coast Guard") {
    const starMatch = context.match(/(\d+)\s*(STAR|STR|\*)/);
    if (starMatch) {
      const count = parseInt(starMatch[1], 10);
      const goldStars = Math.floor(count / 25);
      const silverStars = Math.floor((count % 25) / 5);
      const bronzeStars = count % 5;

      for (let i = 0; i < goldStars; i++) {
        devices.push({ type: "gold_star", position: i });
      }
      for (let i = 0; i < silverStars; i++) {
        devices.push({ type: "silver_star", position: goldStars + i });
      }
      for (let i = 0; i < bronzeStars; i++) {
        devices.push({
          type: "bronze_star",
          position: goldStars + silverStars + i,
        });
      }
    }
  }

  // Arrowhead device
  if (/ARROWHEAD|ARROW/.test(context)) {
    devices.push({ type: "arrowhead", position: 0 });
  }

  return devices;
}

/**
 * Extract text context around a match
 */
function extractContext(text, match, chars) {
  const index = text.indexOf(match);
  if (index === -1) return text;

  const start = Math.max(0, index - chars);
  const end = Math.min(text.length, index + match.length + chars);
  return text.substring(start, end);
}

/**
 * Detect quantity of awards
 */
function detectQuantity(text, awardMatch) {
  const context = extractContext(text, awardMatch, 30);

  // Look for patterns like "(2)", "x2", "2nd", etc.
  const patterns = [/\((\d+)\)/, /x(\d+)/i, /(\d+)(?:ST|ND|RD|TH)\s*AWARD/i];

  for (const pattern of patterns) {
    const match = context.match(pattern);
    if (match) {
      return parseInt(match[1], 10);
    }
  }

  return 1;
}

// ============================================================================
// PRECEDENCE SORTING
// ============================================================================

/**
 * Sort ribbons by branch-specific order of precedence
 * @param {Array} awards - Array of award objects from parseDD214Text
 * @param {string} branch - Branch of service
 * @returns {Array} Sorted awards
 */
export function sortRibbonsByPrecedence(awards, branch) {
  if (!awards || !Array.isArray(awards)) {
    return [];
  }

  return [...awards].sort((a, b) => {
    const precedenceA = a.award?.precedence?.[branch] ?? 999;
    const precedenceB = b.award?.precedence?.[branch] ?? 999;
    return precedenceA - precedenceB;
  });
}

/**
 * Get an award by ID
 */
export function getAwardById(awardId) {
  return MASTER_AWARDS.find((a) => a.id === awardId) || null;
}

/**
 * Get awards applicable to a specific branch
 */
export function getAwardsForBranch(branch) {
  return MASTER_AWARDS.filter((a) => a.branch.includes(branch)).sort(
    (a, b) => (a.precedence[branch] || 999) - (b.precedence[branch] || 999),
  );
}

// ============================================================================
// RACK LAYOUT CALCULATIONS
// ============================================================================

/**
 * Calculate ribbon rack layout
 * @param {Array} sortedAwards - Awards sorted by precedence
 * @param {number} ribbonsPerRow - Ribbons per row (3 or 4)
 * @returns {Array} Array of rows, each containing ribbon objects
 */
export function calculateRackLayout(sortedAwards, ribbonsPerRow = 3) {
  if (!sortedAwards || sortedAwards.length === 0) {
    return [];
  }

  const rows = [];
  const totalRibbons = sortedAwards.length;

  // Calculate how many full rows and remainder
  const fullRows = Math.floor(totalRibbons / ribbonsPerRow);
  const remainder = totalRibbons % ribbonsPerRow;

  let index = 0;

  // Top row (may be partial - should be centered)
  if (remainder > 0) {
    const topRow = {
      ribbons: sortedAwards.slice(index, index + remainder),
      isPartial: true,
      count: remainder,
      alignment: "center",
    };
    rows.push(topRow);
    index += remainder;
  }

  // Full rows
  while (index < totalRibbons) {
    const row = {
      ribbons: sortedAwards.slice(index, index + ribbonsPerRow),
      isPartial: false,
      count: ribbonsPerRow,
      alignment: "full",
    };
    rows.push(row);
    index += ribbonsPerRow;
  }

  return rows;
}

// ============================================================================
// UTILITY EXPORTS
// ============================================================================

export default {
  MASTER_AWARDS,
  DEVICES,
  PRECEDENCE_REGULATIONS,
  parseDD214Text,
  sortRibbonsByPrecedence,
  getAwardById,
  getAwardsForBranch,
  calculateRackLayout,
};
