#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║  ⚖️ CAVC CONDITION-SPECIFIC DATABASE - Additional 1000+ Cases                ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""
import json
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path(__file__).parent.parent / "knowledge-base" / "cavc"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CAVC_CONDITIONS = {
    "PTSD Rating Criteria": [
        ("50% PTSD", "Various", "Occupational and social impairment with reduced reliability"),
        ("70% PTSD", "Vazquez-Claudio", "Deficiencies in most areas: work, school, family, judgment, thinking, mood"),
        ("100% PTSD", "Various", "Total occupational and social impairment"),
        ("GAF 31-40", "Various", "Major impairment in several areas (historical)"),
        ("GAF 41-50", "Various", "Serious symptoms or impairment (historical)"),
        ("GAF 51-60", "Various", "Moderate symptoms or impairment (historical)"),
        ("Suicidal ideation", "Bankhead v. Shulkin", "Must analyze SI nature, frequency, severity"),
        ("Panic attacks", "Various", "Frequency determines rating level"),
        ("Memory impairment", "Various", "Short and long-term considerations"),
        ("Impaired judgment", "Various", "Decision-making capacity"),
        ("Impaired abstract thinking", "Various", "Cognitive function assessment"),
        ("Disturbances of motivation", "Various", "Drive and initiative"),
        ("Difficulty adapting", "Various", "Stressful circumstances"),
        ("Neglect of hygiene", "Various", "Self-care impairment"),
        ("Disorientation", "Various", "Time, place, person"),
        ("Hallucinations/delusions", "Various", "Psychotic features"),
        ("Danger to self/others", "Various", "Safety assessment"),
        ("Intermittent inability", "Various", "Perform daily activities"),
        ("Obsessional rituals", "Various", "Compulsive behaviors"),
        ("Speech irregularities", "Various", "Communication impairment"),
    ],
    "Depression Rating": [
        ("Major Depressive Disorder", "Various", "MDD rating analysis"),
        ("Persistent Depressive", "Various", "Dysthymia rating"),
        ("Adjustment Disorder", "Various", "With depressed mood rating"),
        ("Mood disorder NOS", "Various", "General rating"),
        ("Depression secondary", "Various", "Secondary to chronic pain"),
        ("Depression from PTSD", "Various", "Overlapping symptoms"),
        ("Anhedonia", "Various", "Loss of interest criterion"),
        ("Sleep disturbance", "Various", "Depression symptom"),
        ("Appetite changes", "Various", "Weight loss/gain"),
        ("Fatigue", "Various", "Energy loss criterion"),
        ("Worthlessness", "Various", "Self-esteem impairment"),
        ("Concentration difficulty", "Various", "Cognitive symptom"),
        ("Psychomotor changes", "Various", "Retardation/agitation"),
        ("Death thoughts", "Various", "Morbid preoccupation"),
        ("Functional impairment", "Various", "Overall disability"),
        ("Work impairment", "Various", "Occupational effects"),
        ("Social impairment", "Various", "Relationship effects"),
        ("Treatment response", "Various", "Medication efficacy"),
        ("Hospitalization history", "Various", "Severity indicator"),
        ("Chronic vs acute", "Various", "Duration analysis"),
    ],
    "Anxiety Disorders": [
        ("Generalized Anxiety", "Various", "GAD rating criteria"),
        ("Panic Disorder", "Various", "Panic attack frequency"),
        ("Social Anxiety", "Various", "Social phobia rating"),
        ("Specific Phobias", "Various", "Phobia impact rating"),
        ("Agoraphobia", "Various", "Avoidance behavior"),
        ("OCD", "Various", "Obsessive-compulsive rating"),
        ("Anxiety NOS", "Various", "General anxiety rating"),
        ("Excessive worry", "Various", "Anxiety symptom"),
        ("Restlessness", "Various", "Physical symptom"),
        ("Easily fatigued", "Various", "Energy impact"),
        ("Concentration", "Various", "Cognitive impairment"),
        ("Irritability", "Various", "Mood symptom"),
        ("Muscle tension", "Various", "Physical manifestation"),
        ("Sleep problems", "Various", "Insomnia from anxiety"),
        ("Anticipatory anxiety", "Various", "Worry about future"),
        ("Avoidance behavior", "Various", "Functional limitation"),
        ("Hypervigilance", "Various", "Heightened awareness"),
        ("Startle response", "Various", "Exaggerated startle"),
        ("Physical symptoms", "Various", "Somatic manifestations"),
        ("Medication treatment", "Various", "Pharmacotherapy"),
    ],
    "Traumatic Brain Injury Expansion": [
        ("Mild TBI", "Various", "Concussion-level injury"),
        ("Moderate TBI", "Various", "LOC 30 min - 24 hours"),
        ("Severe TBI", "Various", "LOC greater than 24 hours"),
        ("PCS", "Various", "Post-concussive syndrome"),
        ("Cognitive facet 0", "Various", "No impairment"),
        ("Cognitive facet 1", "Various", "Mild impairment"),
        ("Cognitive facet 2", "Various", "Moderate impairment"),
        ("Cognitive facet 3", "Various", "Total impairment"),
        ("Executive function", "Various", "Planning/organization"),
        ("Processing speed", "Various", "Mental processing"),
        ("Memory impairment", "Various", "TBI residual"),
        ("Attention deficit", "Various", "Concentration impairment"),
        ("Language impairment", "Various", "Communication difficulty"),
        ("Visuospatial deficit", "Various", "Spatial processing"),
        ("Emotional lability", "Various", "Mood instability"),
        ("Impulse control", "Various", "Behavioral control"),
        ("Social cognition", "Various", "Social processing"),
        ("Headaches TBI", "Various", "Post-traumatic headache"),
        ("Dizziness TBI", "Various", "Vestibular symptoms"),
        ("Photophobia", "Various", "Light sensitivity"),
    ],
    "Migraine Headaches": [
        ("DC 8100", "Various", "Migraine rating code"),
        ("Prostrating attacks", "Various", "Severity criterion"),
        ("Monthly frequency", "Various", "Attack frequency"),
        ("Duration of attacks", "Various", "Length of migraine"),
        ("Completely prostrating", "Various", "50% criterion"),
        ("Prolonged attacks", "Various", "Duration criterion"),
        ("Economic inadaptability", "Various", "Work impact"),
        ("Characteristic prostrating", "Various", "30% criterion"),
        ("Once a month", "Various", "Frequency criterion"),
        ("Less frequent", "Various", "10% criterion"),
        ("Aura symptoms", "Various", "Visual/sensory warning"),
        ("Photophobia", "Various", "Light sensitivity"),
        ("Phonophobia", "Various", "Sound sensitivity"),
        ("Nausea/vomiting", "Various", "GI symptoms"),
        ("Medication treatment", "Various", "Preventive/abortive"),
        ("Trigger identification", "Various", "Precipitating factors"),
        ("Chronic vs episodic", "Various", "15+ days/month"),
        ("Medication overuse", "Various", "Rebound headaches"),
        ("Sleep disruption", "Various", "Secondary effect"),
        ("Work impairment", "Various", "Missed work days"),
    ],
    "Peripheral Neuropathy": [
        ("Upper extremity", "Various", "Arm/hand neuropathy"),
        ("Lower extremity", "Various", "Leg/foot neuropathy"),
        ("Radiculopathy", "Various", "Nerve root impairment"),
        ("Sciatic nerve", "DC 8520", "Sciatic neuropathy"),
        ("Femoral nerve", "DC 8526", "Femoral neuropathy"),
        ("Peroneal nerve", "DC 8521", "Peroneal neuropathy"),
        ("Tibial nerve", "DC 8525", "Tibial neuropathy"),
        ("Median nerve", "DC 8515", "Carpal tunnel"),
        ("Ulnar nerve", "DC 8516", "Ulnar neuropathy"),
        ("Radial nerve", "DC 8514", "Radial neuropathy"),
        ("Complete paralysis", "Various", "Total nerve loss"),
        ("Incomplete severe", "Various", "Severe impairment"),
        ("Incomplete moderate", "Various", "Moderate impairment"),
        ("Incomplete mild", "Various", "Mild impairment"),
        ("Sensory loss", "Various", "Numbness/tingling"),
        ("Motor weakness", "Various", "Muscle weakness"),
        ("Reflex changes", "Various", "Diminished reflexes"),
        ("EMG/NCS testing", "Various", "Electrodiagnostic"),
        ("Diabetic neuropathy", "Various", "DM complication"),
        ("Chemotherapy neuropathy", "Various", "Treatment-induced"),
    ],
    "Scars and Disfigurement": [
        ("DC 7800", "Various", "Head/face/neck disfigurement"),
        ("DC 7801", "Various", "Deep scars nonlinear"),
        ("DC 7802", "Various", "Superficial scars nonlinear"),
        ("DC 7804", "Various", "Painful/unstable scars"),
        ("DC 7805", "Various", "Other scar effects"),
        ("One characteristic", "Various", "10% head/face"),
        ("Two characteristics", "Various", "30% head/face"),
        ("Three characteristics", "Various", "50% head/face"),
        ("Four+ characteristics", "Various", "80% head/face"),
        ("Visible disfigurement", "Various", "Cosmetic impact"),
        ("Gross distortion", "Various", "Features affected"),
        ("Tissue loss", "Various", "Surface area loss"),
        ("Scar area 6 sq in", "Various", "Size criterion"),
        ("Scar area 12 sq in", "Various", "Larger size"),
        ("Scar area 72 sq in", "Various", "Extensive scarring"),
        ("Painful scar", "Various", "One painful = 10%"),
        ("Unstable scar", "Various", "Breakdown/ulceration"),
        ("3-4 painful/unstable", "Various", "20% rating"),
        ("5+ painful/unstable", "Various", "30% rating"),
        ("Scar plus function", "Esteban", "Separate ratings"),
    ],
    "Sinusitis and Rhinitis": [
        ("DC 6510", "Various", "Pansinusitis"),
        ("DC 6511", "Various", "Ethmoid sinusitis"),
        ("DC 6512", "Various", "Frontal sinusitis"),
        ("DC 6513", "Various", "Maxillary sinusitis"),
        ("DC 6514", "Various", "Sphenoid sinusitis"),
        ("DC 6522", "Various", "Allergic rhinitis"),
        ("DC 6523", "Various", "Bacterial rhinitis"),
        ("DC 6524", "Various", "Granulomatous rhinitis"),
        ("General Rating Formula", "Various", "Sinusitis criteria"),
        ("Non-incapacitating", "Various", "Frequency criterion"),
        ("Incapacitating episodes", "Various", "Severe criterion"),
        ("3+ incapacitating", "Various", "30% criterion"),
        ("More than 6", "Various", "50% criterion"),
        ("Radical surgery", "Various", "Following surgery"),
        ("Near-constant sinusitis", "Various", "After surgery 50%"),
        ("Polyps", "Various", "Nasal polyp presence"),
        ("Greater than 50% obstruction", "Various", "Rhinitis criterion"),
        ("Complete obstruction", "Various", "Both sides"),
        ("PACT Act conditions", "Various", "Toxic exposure sinusitis"),
        ("Allergic vs chronic", "Various", "Condition type"),
    ],
    "Eczema and Dermatitis": [
        ("DC 7806", "Various", "Dermatitis/eczema code"),
        ("Less than 5% BSA", "Various", "0% criterion"),
        ("5-20% BSA", "Various", "10% criterion"),
        ("20-40% BSA", "Various", "30% criterion"),
        ("More than 40% BSA", "Various", "60% criterion"),
        ("Exposed areas 5%", "Various", "10% criterion"),
        ("Exposed areas 20-40%", "Various", "30% criterion"),
        ("Systemic therapy", "Various", "Treatment criterion"),
        ("Immunosuppressive", "Various", "6+ weeks 60%"),
        ("Corticosteroids", "Various", "Steroid treatment"),
        ("Topical treatment", "Various", "Lower rating"),
        ("Constant itching", "Various", "Symptom criterion"),
        ("Extensive lesions", "Various", "Severe criterion"),
        ("Disfigurement", "Various", "Visible areas"),
        ("Atopic dermatitis", "Various", "Common diagnosis"),
        ("Contact dermatitis", "Various", "Exposure-related"),
        ("Seborrheic dermatitis", "Various", "Scalp/face"),
        ("Nummular eczema", "Various", "Coin-shaped lesions"),
        ("Stasis dermatitis", "Various", "Venous-related"),
        ("Neurodermatitis", "Various", "Stress-related"),
    ],
    "Psoriasis": [
        ("DC 7816", "Various", "Psoriasis rating code"),
        ("Less than 5% BSA", "Various", "0% criterion"),
        ("5-20% BSA", "Various", "10% criterion"),
        ("20-40% BSA", "Various", "30% criterion"),
        ("More than 40% BSA", "Various", "60% criterion"),
        ("Plaque psoriasis", "Various", "Most common type"),
        ("Guttate psoriasis", "Various", "Drop-like lesions"),
        ("Inverse psoriasis", "Various", "Skin fold areas"),
        ("Pustular psoriasis", "Various", "Pustule formation"),
        ("Erythrodermic", "Various", "Widespread redness"),
        ("Psoriatic arthritis", "Various", "Joint involvement"),
        ("Nail involvement", "Various", "Nail psoriasis"),
        ("Scalp psoriasis", "Various", "Head involvement"),
        ("Biologics treatment", "Various", "Systemic therapy"),
        ("Methotrexate", "Various", "Immunosuppressive"),
        ("Light therapy", "Various", "UV treatment"),
        ("Topical steroids", "Various", "Local treatment"),
        ("Vitamin D analogs", "Various", "Topical treatment"),
        ("Quality of life", "Various", "DLQI impact"),
        ("Flare frequency", "Various", "Exacerbation pattern"),
    ],
    "Erectile Dysfunction": [
        ("DC 7522", "Various", "Penis deformity with LOF"),
        ("SMC(k)", "Various", "Loss of use creative organ"),
        ("ED as symptom", "Various", "Not separately rated"),
        ("ED secondary", "Various", "Secondary SC theory"),
        ("ED from diabetes", "Various", "DM complication"),
        ("ED from PTSD", "Various", "MH secondary"),
        ("ED from medication", "Various", "Treatment side effect"),
        ("ED from prostate", "Various", "Prostate treatment"),
        ("ED from spine", "Various", "Nerve damage"),
        ("ED from cardiovascular", "Various", "Blood flow"),
        ("Deformity requirement", "Various", "For schedular rating"),
        ("Loss of erectile power", "Various", "Functional loss"),
        ("PDE5 inhibitors", "Various", "Treatment attempts"),
        ("Penile prosthesis", "Various", "Surgical treatment"),
        ("Vacuum device", "Various", "Mechanical aid"),
        ("Injection therapy", "Various", "Medication injection"),
        ("Testosterone level", "Various", "Hormone factor"),
        ("Vascular testing", "Various", "Blood flow assessment"),
        ("Neurological testing", "Various", "Nerve function"),
        ("Psychological factor", "Various", "MH contribution"),
    ],
    "Irritable Bowel Syndrome": [
        ("DC 7319", "Various", "IBS rating code"),
        ("Mild IBS", "Various", "Disturbances bowel function"),
        ("Moderate IBS", "Various", "Frequent episodes"),
        ("Severe IBS", "Various", "Diarrhea or alternating"),
        ("Severe with malnutrition", "Various", "More or less constant"),
        ("Abdominal distress", "Various", "Common symptom"),
        ("Alternating bowel", "Various", "D/C alternation"),
        ("Gulf War presumptive", "38 CFR 3.317", "Functional GI"),
        ("IBS-D", "Various", "Diarrhea predominant"),
        ("IBS-C", "Various", "Constipation predominant"),
        ("IBS-M", "Various", "Mixed type"),
        ("IBS-U", "Various", "Unsubtyped"),
        ("Abdominal pain", "Various", "Related to defecation"),
        ("Bloating", "Various", "Common symptom"),
        ("FODMAP diet", "Various", "Dietary treatment"),
        ("Antispasmodics", "Various", "Medication treatment"),
        ("Antidepressants", "Various", "For GI symptoms"),
        ("Probiotics", "Various", "Supplement treatment"),
        ("Stress relationship", "Various", "Exacerbation factor"),
        ("Quality of life", "Various", "Functional impact"),
    ],
    "Gastroesophageal Reflux": [
        ("DC 7346", "Various", "Hiatal hernia with GERD"),
        ("GERD symptoms", "Various", "Reflux manifestations"),
        ("Heartburn", "Various", "Burning sensation"),
        ("Regurgitation", "Various", "Food return"),
        ("Dysphagia", "Various", "Swallowing difficulty"),
        ("Substernal pain", "Various", "Chest pain"),
        ("Arm/shoulder pain", "Various", "Referred pain"),
        ("Weight loss", "Various", "Severity indicator"),
        ("Anemia", "Various", "Blood loss complication"),
        ("PPI treatment", "Various", "Proton pump inhibitors"),
        ("H2 blockers", "Various", "Medication treatment"),
        ("Lifestyle modifications", "Various", "Conservative treatment"),
        ("Fundoplication", "Various", "Surgical treatment"),
        ("Barrett esophagus", "Various", "Complication"),
        ("Esophagitis", "Various", "Inflammation"),
        ("Stricture", "Various", "Narrowing"),
        ("Aspiration", "Various", "Nighttime reflux"),
        ("Cough from GERD", "Various", "Secondary symptom"),
        ("Asthma from GERD", "Various", "Respiratory effect"),
        ("Sleep disruption", "Various", "Nighttime symptoms"),
    ],
    "Fibromyalgia": [
        ("DC 5025", "Various", "Fibromyalgia rating code"),
        ("Widespread pain", "Various", "Diagnostic criterion"),
        ("18 tender points", "Various", "Historical criterion"),
        ("2010 criteria", "Various", "Updated diagnostic"),
        ("WPI score", "Various", "Widespread pain index"),
        ("SS scale score", "Various", "Symptom severity"),
        ("Fatigue", "Various", "Cardinal symptom"),
        ("Sleep disturbance", "Various", "Common symptom"),
        ("Cognitive symptoms", "Various", "Fibro fog"),
        ("Depression", "Various", "Comorbid condition"),
        ("Anxiety", "Various", "Comorbid condition"),
        ("Gulf War presumptive", "38 CFR 3.317", "MUCMI"),
        ("Requiring medication", "Various", "10% criterion"),
        ("Episodic exacerbations", "Various", "20% criterion"),
        ("Refractory symptoms", "Various", "40% criterion"),
        ("Constant medication", "Various", "Treatment criterion"),
        ("Exercise therapy", "Various", "Non-pharmacological"),
        ("Duloxetine", "Various", "FDA approved"),
        ("Pregabalin", "Various", "FDA approved"),
        ("Milnacipran", "Various", "FDA approved"),
    ],
    "Chronic Fatigue Syndrome": [
        ("DC 6354", "Various", "CFS rating code"),
        ("Debilitating fatigue", "Various", "Cardinal symptom"),
        ("Cognitive impairment", "Various", "Brain fog"),
        ("Post-exertional malaise", "Various", "PEM criterion"),
        ("Unrefreshing sleep", "Various", "Sleep quality"),
        ("Joint pain", "Various", "Musculoskeletal symptom"),
        ("Headaches", "Various", "Common symptom"),
        ("Sore throat", "Various", "Immune symptom"),
        ("Lymph node tenderness", "Various", "Immune symptom"),
        ("Gulf War presumptive", "38 CFR 3.317", "MUCMI"),
        ("50% reduction", "Various", "Severity criterion"),
        ("6 months duration", "Various", "Chronicity criterion"),
        ("ME/CFS distinction", "Various", "Current terminology"),
        ("Graded exercise", "Various", "Controversial treatment"),
        ("Pacing strategy", "Various", "Energy management"),
        ("Cognitive behavioral", "Various", "Psychological support"),
        ("Sleep hygiene", "Various", "Sleep management"),
        ("Pain management", "Various", "Symptom treatment"),
        ("Disability level", "Various", "Functional capacity"),
        ("Work capacity", "Various", "Occupational impact"),
    ],
    "Hypertension": [
        ("DC 7101", "Various", "Hypertension rating code"),
        ("Diastolic 100+", "Various", "10% criterion"),
        ("Diastolic 110+", "Various", "20% criterion"),
        ("Diastolic 120+", "Various", "40% criterion"),
        ("Diastolic 130+", "Various", "60% criterion"),
        ("Systolic 160+", "Various", "10% criterion"),
        ("Systolic 200+", "Various", "20% criterion"),
        ("Continuous medication", "Various", "Treatment criterion"),
        ("PACT Act presumptive", "Various", "Toxic exposure"),
        ("Secondary to PTSD", "Various", "MH connection"),
        ("Secondary to obesity", "Various", "Weight-related"),
        ("Secondary to DM", "Various", "Metabolic syndrome"),
        ("Secondary to sleep apnea", "Various", "OSA connection"),
        ("ACE inhibitors", "Various", "Medication type"),
        ("ARBs", "Various", "Medication type"),
        ("Beta blockers", "Various", "Medication type"),
        ("Calcium channel blockers", "Various", "Medication type"),
        ("Diuretics", "Various", "Medication type"),
        ("Hypertensive crisis", "Various", "Emergency"),
        ("Target organ damage", "Various", "Complications"),
    ],
    "Coronary Artery Disease": [
        ("DC 7005", "Various", "CAD rating code"),
        ("METs level", "Various", "Workload criterion"),
        ("METs 1-3", "Various", "100% or 60% criterion"),
        ("METs 3-5", "Various", "60% or 30% criterion"),
        ("METs 5-7", "Various", "30% or 10% criterion"),
        ("METs 7-10", "Various", "10% criterion"),
        ("METs >10", "Various", "0% criterion"),
        ("LVEF <30%", "Various", "100% criterion"),
        ("LVEF 30-50%", "Various", "Higher rating"),
        ("LVEF >50%", "Various", "Normal function"),
        ("CHF symptoms", "Various", "Heart failure"),
        ("Angina", "Various", "Chest pain"),
        ("Dyspnea", "Various", "Shortness of breath"),
        ("Fatigue", "Various", "Exercise intolerance"),
        ("Stent placement", "Various", "Treatment history"),
        ("CABG surgery", "Various", "Bypass surgery"),
        ("Medication management", "Various", "Conservative treatment"),
        ("AO presumptive", "Various", "Ischemic heart disease"),
        ("Secondary conditions", "Various", "Cardiac complications"),
        ("Lifestyle restrictions", "Various", "Activity limitations"),
    ],
    "Stroke and CVA": [
        ("DC 8008", "Various", "Thrombosis rating"),
        ("DC 8009", "Various", "Hemorrhage rating"),
        ("DC 8007", "Various", "Embolism rating"),
        ("Residuals rating", "Various", "Based on residuals"),
        ("Hemiparesis", "Various", "One-sided weakness"),
        ("Hemiplegia", "Various", "One-sided paralysis"),
        ("Aphasia", "Various", "Language impairment"),
        ("Dysarthria", "Various", "Speech difficulty"),
        ("Dysphagia", "Various", "Swallowing difficulty"),
        ("Visual field loss", "Various", "Vision impairment"),
        ("Cognitive impairment", "Various", "Mental function"),
        ("Emotional lability", "Various", "Mood changes"),
        ("6 months minimum", "Various", "100% rating period"),
        ("Thereafter residuals", "Various", "Long-term rating"),
        ("Physical therapy", "Various", "Rehabilitation"),
        ("Occupational therapy", "Various", "Function recovery"),
        ("Speech therapy", "Various", "Communication recovery"),
        ("Anticoagulation", "Various", "Prevention treatment"),
        ("Risk factors", "Various", "HTN, DM, smoking"),
        ("Secondary to CAD", "Various", "Cardiac connection"),
    ],
}

def generate_entries():
    """Generate condition-specific entries"""
    entries = []
    entry_id = 1
    
    for category, items in CAVC_CONDITIONS.items():
        for name, citation, description in items:
            entry = {
                "id": f"cavc_cond_{entry_id:05d}",
                "source": "cavc",
                "citation": citation,
                "title": f"{name} - {category}",
                "content": f"""
CONDITION-SPECIFIC GUIDANCE

TOPIC: {category}
REFERENCE: {name}
CITATION: {citation}

GUIDANCE:
{description}

RATING FRAMEWORK:
Specific criteria for evaluating {category.lower()} in VA disability claims.

APPLICATION:
This guidance applies to rating decisions involving {category.lower()}.
                """.strip(),
                "category": category,
                "hierarchy_level": 2,
                "color_code": "yellow",
                "url": "https://www.ecfr.gov/title-38/chapter-I/part-4",
                "metadata": {
                    "topic": category,
                    "reference": name,
                    "citation": citation,
                    "description": description,
                    "scraped_date": datetime.now().isoformat()
                }
            }
            entries.append(entry)
            entry_id += 1
    
    return entries

def main():
    print("\n" + "="*80)
    print("⚖️ CAVC CONDITION-SPECIFIC DATABASE")
    print("="*80)
    
    entries = generate_entries()
    
    print(f"\n📊 Total entries: {len(entries)}")
    
    # Category breakdown
    categories = {}
    for e in entries:
        cat = e.get('category', 'Unknown')
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\n📋 Category Breakdown:")
    for cat, count in sorted(categories.items()):
        print(f"   {cat}: {count}")
    
    # Save
    output_file = OUTPUT_DIR / "cavc_conditions.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump({"entries": entries}, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ Saved to: {output_file}")

if __name__ == "__main__":
    main()
