#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║  ⚖️ CAVC BODY SYSTEMS DEEP DIVE - 800+ Comprehensive Entries                 ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""
import json
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path(__file__).parent.parent / "knowledge-base" / "cavc"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BODY_SYSTEMS = {
    "Musculoskeletal Cervical Spine": [
        ("Cervical Strain", "Various", "Neck strain rating"),
        ("Cervical DDD", "Various", "Degenerative disc disease"),
        ("Cervical DJD", "Various", "Degenerative joint disease"),
        ("Cervical Stenosis", "Various", "Spinal canal narrowing"),
        ("Cervical Radiculopathy", "Various", "Upper extremity nerve impairment"),
        ("Cervical Myelopathy", "Various", "Spinal cord compression"),
        ("Cervical ACDF", "Various", "Anterior cervical discectomy fusion"),
        ("Cervical PCF", "Various", "Posterior cervical fusion"),
        ("Cervical ROM Forward Flexion", "Various", "Normal 45 degrees"),
        ("Cervical ROM Extension", "Various", "Normal 45 degrees"),
        ("Cervical ROM Lateral Flexion", "Various", "Normal 45 degrees each"),
        ("Cervical ROM Rotation", "Various", "Normal 80 degrees each"),
        ("Cervical Combined ROM", "Various", "340 degrees normal"),
        ("Cervical Muscle Spasm", "Various", "Abnormal gait/spinal contour"),
        ("Cervical Guarding", "Various", "Protective positioning"),
        ("Cervical Ankylosis", "Various", "Unfavorable/favorable"),
        ("Cervical IVDS", "Various", "Incapacitating episodes"),
        ("Cervical Facet Syndrome", "Various", "Facet joint pathology"),
        ("Whiplash Injury", "Various", "Acceleration-deceleration"),
        ("Cervical Spondylosis", "Various", "Age-related changes"),
    ],
    "Musculoskeletal Thoracolumbar Spine": [
        ("Thoracic Strain", "Various", "Mid-back strain rating"),
        ("Thoracic DDD", "Various", "Degenerative disc disease"),
        ("Thoracic DJD", "Various", "Degenerative joint disease"),
        ("Thoracic Kyphosis", "Various", "Excessive curvature"),
        ("Scheuermann's Disease", "Various", "Juvenile kyphosis"),
        ("Lumbar Strain", "Various", "Low back strain"),
        ("Lumbar DDD", "Various", "Degenerative disc disease"),
        ("Lumbar DJD", "Various", "Degenerative joint disease"),
        ("Lumbar Stenosis", "Various", "Spinal canal narrowing"),
        ("Lumbar Spondylolisthesis", "Various", "Vertebral slippage"),
        ("Lumbar Radiculopathy", "Various", "Lower extremity nerve"),
        ("Lumbar Fusion", "Various", "Spinal fusion surgery"),
        ("Lumbar Laminectomy", "Various", "Decompression surgery"),
        ("Lumbar Discectomy", "Various", "Disc removal"),
        ("Lumbar ROM Forward Flexion", "Various", "Normal 90 degrees"),
        ("Lumbar ROM Extension", "Various", "Normal 30 degrees"),
        ("Lumbar ROM Lateral Flexion", "Various", "Normal 30 degrees each"),
        ("Lumbar ROM Rotation", "Various", "Normal 30 degrees each"),
        ("Lumbar Combined ROM", "Various", "240 degrees normal"),
        ("Cauda Equina Syndrome", "Various", "Surgical emergency"),
    ],
    "Musculoskeletal Upper Extremity": [
        ("Wrist Strain", "Various", "Wrist sprain/strain"),
        ("Wrist Tendonitis", "Various", "Tendon inflammation"),
        ("Carpal Tunnel Syndrome", "DC 8515", "Median nerve entrapment"),
        ("De Quervain's", "Various", "Thumb tendon condition"),
        ("Wrist Fracture Residuals", "Various", "Post-fracture sequelae"),
        ("Wrist Arthritis", "Various", "Degenerative changes"),
        ("Wrist ROM Dorsiflexion", "Various", "Normal 70 degrees"),
        ("Wrist ROM Palmar Flexion", "Various", "Normal 80 degrees"),
        ("Wrist ROM Ulnar Deviation", "Various", "Normal 45 degrees"),
        ("Wrist ROM Radial Deviation", "Various", "Normal 20 degrees"),
        ("Elbow Strain", "Various", "Elbow sprain/strain"),
        ("Tennis Elbow", "Various", "Lateral epicondylitis"),
        ("Golfer's Elbow", "Various", "Medial epicondylitis"),
        ("Elbow Bursitis", "Various", "Olecranon bursitis"),
        ("Elbow Fracture Residuals", "Various", "Post-fracture sequelae"),
        ("Elbow Arthritis", "Various", "Degenerative changes"),
        ("Elbow ROM Flexion", "Various", "Normal 145 degrees"),
        ("Elbow ROM Extension", "Various", "Normal 0 degrees"),
        ("Forearm ROM Supination", "Various", "Normal 85 degrees"),
        ("Forearm ROM Pronation", "Various", "Normal 80 degrees"),
    ],
    "Musculoskeletal Lower Extremity": [
        ("Foot Strain", "Various", "Foot sprain/strain"),
        ("Plantar Fasciitis", "Various", "Heel pain condition"),
        ("Achilles Tendinitis", "Various", "Tendon inflammation"),
        ("Achilles Rupture Residuals", "Various", "Post-rupture sequelae"),
        ("Metatarsalgia", "Various", "Forefoot pain"),
        ("Morton's Neuroma", "Various", "Interdigital neuroma"),
        ("Hallux Valgus", "DC 5280", "Bunion deformity"),
        ("Hallux Rigidus", "DC 5281", "Big toe arthritis"),
        ("Hammer Toes", "DC 5282", "Toe deformity"),
        ("Claw Foot", "DC 5278", "Pes cavus"),
        ("Flat Feet", "DC 5276", "Pes planus"),
        ("Foot Drop", "Various", "Peroneal nerve palsy"),
        ("Tarsal Tunnel", "Various", "Posterior tibial nerve"),
        ("Foot Fracture Residuals", "Various", "Post-fracture sequelae"),
        ("Stress Fracture", "Various", "Overuse injury"),
        ("Osteochondral Defect", "Various", "Cartilage damage"),
        ("Shin Splints", "Various", "Medial tibial stress"),
        ("Compartment Syndrome", "Various", "Fascial pressure"),
        ("Calf Strain", "Various", "Gastrocnemius/soleus"),
        ("Quadriceps Strain", "Various", "Thigh muscle injury"),
    ],
    "Cardiovascular Hypertensive": [
        ("Stage 1 Hypertension", "Various", "130-139/80-89 mmHg"),
        ("Stage 2 Hypertension", "Various", "140+/90+ mmHg"),
        ("Hypertensive Crisis", "Various", "180+/120+ mmHg"),
        ("White Coat Hypertension", "Various", "Situational elevation"),
        ("Masked Hypertension", "Various", "Normal office, elevated ambulatory"),
        ("Resistant Hypertension", "Various", "Uncontrolled on 3+ medications"),
        ("Secondary Hypertension", "Various", "Underlying cause identified"),
        ("Essential Hypertension", "Various", "Primary/idiopathic"),
        ("Malignant Hypertension", "Various", "Severe with organ damage"),
        ("Hypertensive Nephropathy", "Various", "Kidney damage from HTN"),
        ("Hypertensive Retinopathy", "Various", "Eye damage from HTN"),
        ("Hypertensive Cardiomyopathy", "Various", "Heart changes from HTN"),
        ("Left Ventricular Hypertrophy", "Various", "LVH from HTN"),
        ("Hypertensive Encephalopathy", "Various", "Brain effects"),
        ("Ambulatory BP Monitoring", "Various", "24-hour monitoring"),
        ("Home BP Monitoring", "Various", "Self-monitoring"),
        ("ACE Inhibitor Treatment", "Various", "Lisinopril, enalapril"),
        ("ARB Treatment", "Various", "Losartan, valsartan"),
        ("Beta Blocker Treatment", "Various", "Metoprolol, atenolol"),
        ("Calcium Channel Blocker", "Various", "Amlodipine, nifedipine"),
    ],
    "Cardiovascular Heart Disease": [
        ("Stable Angina", "Various", "Effort-induced chest pain"),
        ("Unstable Angina", "Various", "Rest pain/ACS"),
        ("NSTEMI", "Various", "Non-ST elevation MI"),
        ("STEMI", "Various", "ST elevation MI"),
        ("Prinzmetal Angina", "Various", "Vasospastic angina"),
        ("Cardiac Syndrome X", "Various", "Microvascular angina"),
        ("Heart Failure HFrEF", "Various", "Reduced ejection fraction"),
        ("Heart Failure HFpEF", "Various", "Preserved ejection fraction"),
        ("Diastolic Dysfunction", "Various", "Impaired relaxation"),
        ("Systolic Dysfunction", "Various", "Impaired contraction"),
        ("Atrial Fibrillation", "DC 7010", "Irregular rhythm"),
        ("Atrial Flutter", "DC 7010", "Rapid atrial rhythm"),
        ("Ventricular Tachycardia", "DC 7011", "V-tach"),
        ("Bradycardia", "Various", "Slow heart rate"),
        ("Heart Block", "DC 7015", "AV conduction abnormality"),
        ("Pacemaker Dependent", "DC 7018", "Electronic device"),
        ("AICD", "DC 7018", "Implantable defibrillator"),
        ("Valve Disease Mitral", "DC 7000", "Mitral valve pathology"),
        ("Valve Disease Aortic", "DC 7000", "Aortic valve pathology"),
        ("Cardiomyopathy Dilated", "DC 7020", "Enlarged heart"),
    ],
    "Respiratory COPD/Asthma": [
        ("Chronic Bronchitis", "DC 6600", "Productive cough"),
        ("Emphysema", "DC 6603", "Alveolar destruction"),
        ("COPD Mild", "Various", "FEV1 80%+ predicted"),
        ("COPD Moderate", "Various", "FEV1 50-79% predicted"),
        ("COPD Severe", "Various", "FEV1 30-49% predicted"),
        ("COPD Very Severe", "Various", "FEV1 <30% predicted"),
        ("GOLD Stage I", "Various", "Mild airflow limitation"),
        ("GOLD Stage II", "Various", "Moderate airflow"),
        ("GOLD Stage III", "Various", "Severe airflow"),
        ("GOLD Stage IV", "Various", "Very severe airflow"),
        ("Alpha-1 Antitrypsin", "Various", "Genetic emphysema"),
        ("Bronchiectasis", "Various", "Airway dilation"),
        ("Asthma Intermittent", "DC 6602", "Symptoms <2x/week"),
        ("Asthma Mild Persistent", "DC 6602", "Symptoms >2x/week"),
        ("Asthma Moderate Persistent", "DC 6602", "Daily symptoms"),
        ("Asthma Severe Persistent", "DC 6602", "Throughout day symptoms"),
        ("Exercise-Induced Asthma", "Various", "Exertion-triggered"),
        ("Occupational Asthma", "Various", "Workplace exposure"),
        ("Allergic Asthma", "Various", "IgE-mediated"),
        ("Non-Allergic Asthma", "Various", "Non-IgE triggers"),
    ],
    "Respiratory Sleep Disorders": [
        ("Obstructive Sleep Apnea Mild", "Various", "AHI 5-14"),
        ("Obstructive Sleep Apnea Moderate", "Various", "AHI 15-29"),
        ("Obstructive Sleep Apnea Severe", "Various", "AHI 30+"),
        ("Central Sleep Apnea", "Various", "Central respiratory drive"),
        ("Complex Sleep Apnea", "Various", "Mixed etiology"),
        ("Obesity Hypoventilation", "Various", "OHS/Pickwickian"),
        ("Upper Airway Resistance", "Various", "UARS"),
        ("Positional OSA", "Various", "Supine-dependent"),
        ("REM-Related OSA", "Various", "REM sleep specific"),
        ("Hypopnea", "Various", "Partial airway collapse"),
        ("Desaturation Events", "Various", "Oxygen drops"),
        ("Arousal Index", "Various", "Sleep fragmentation"),
        ("Sleep Efficiency", "Various", "Time asleep/time in bed"),
        ("CPAP Therapy", "Various", "Continuous positive airway"),
        ("BiPAP Therapy", "Various", "Bilevel positive airway"),
        ("APAP Therapy", "Various", "Auto-titrating positive"),
        ("Oral Appliance", "Various", "Mandibular advancement"),
        ("Positional Therapy", "Various", "Sleep position modification"),
        ("Nasal Surgery OSA", "Various", "Septoplasty/turbinates"),
        ("UPPP Surgery", "Various", "Uvulopalatopharyngoplasty"),
    ],
    "Gastrointestinal Upper GI": [
        ("Esophagitis", "Various", "Esophageal inflammation"),
        ("Barrett's Esophagus", "Various", "Metaplasia"),
        ("Esophageal Stricture", "Various", "Narrowing"),
        ("Esophageal Spasm", "Various", "Dysmotility"),
        ("Achalasia", "Various", "LES dysfunction"),
        ("Hiatal Hernia Sliding", "Various", "Type I hernia"),
        ("Hiatal Hernia Paraesophageal", "Various", "Type II-IV hernia"),
        ("Gastritis Acute", "Various", "Acute inflammation"),
        ("Gastritis Chronic", "Various", "Chronic inflammation"),
        ("Gastritis H. pylori", "Various", "Bacterial infection"),
        ("Gastritis Autoimmune", "Various", "Pernicious anemia"),
        ("Peptic Ulcer Disease", "Various", "Stomach/duodenal ulcers"),
        ("Gastric Ulcer", "DC 7304", "Stomach ulcer"),
        ("Duodenal Ulcer", "DC 7305", "Duodenal ulcer"),
        ("Gastric Polyps", "Various", "Benign growths"),
        ("Gastroparesis", "Various", "Delayed gastric emptying"),
        ("Dumping Syndrome", "Various", "Post-gastrectomy"),
        ("Zollinger-Ellison", "Various", "Gastrinoma"),
        ("PPI Treatment", "Various", "Proton pump inhibitors"),
        ("H2 Blocker Treatment", "Various", "Acid reduction"),
    ],
    "Gastrointestinal Lower GI": [
        ("Ulcerative Colitis", "DC 7323", "UC rating"),
        ("Crohn's Disease", "DC 7323", "Regional enteritis"),
        ("Microscopic Colitis", "Various", "Collagenous/lymphocytic"),
        ("Diverticulosis", "Various", "Diverticula present"),
        ("Diverticulitis", "DC 7327", "Diverticula inflammation"),
        ("Colonic Polyps", "Various", "Adenomatous/hyperplastic"),
        ("Colon Cancer Post-Resection", "Various", "Post-surgery residuals"),
        ("Colostomy", "DC 7329", "Surgical ostomy"),
        ("Ileostomy", "DC 7329", "Small bowel ostomy"),
        ("Hemorrhoids Internal", "DC 7336", "Inside rectum"),
        ("Hemorrhoids External", "DC 7336", "Outside rectum"),
        ("Anal Fissure", "Various", "Tear in anal canal"),
        ("Anal Fistula", "DC 7330", "Abnormal tract"),
        ("Rectal Prolapse", "Various", "Rectal protrusion"),
        ("Proctitis", "Various", "Rectal inflammation"),
        ("Fecal Incontinence", "DC 7332", "Loss of bowel control"),
        ("Constipation Chronic", "Various", "Functional constipation"),
        ("Small Bowel Obstruction", "Various", "SBO"),
        ("Adhesive Disease", "DC 7301", "Peritoneal adhesions"),
        ("Short Bowel Syndrome", "Various", "Malabsorption"),
    ],
    "Genitourinary Male": [
        ("Benign Prostatic Hyperplasia", "Various", "BPH"),
        ("Prostatitis Acute", "Various", "Bacterial prostatitis"),
        ("Prostatitis Chronic", "Various", "CP/CPPS"),
        ("Prostate Cancer Residuals", "Various", "Post-treatment"),
        ("Radical Prostatectomy", "Various", "Surgical removal"),
        ("Radiation Prostate", "Various", "RT residuals"),
        ("PSA Elevation", "Various", "Monitoring"),
        ("Urinary Retention", "DC 7517", "Inability to void"),
        ("Urinary Frequency", "Various", "Voiding symptom"),
        ("Urinary Urgency", "Various", "Sudden urge"),
        ("Nocturia", "Various", "Nighttime voiding"),
        ("Weak Stream", "Various", "Reduced flow"),
        ("Incomplete Emptying", "Various", "Residual urine"),
        ("Epididymitis", "DC 7525", "Epididymal inflammation"),
        ("Orchitis", "Various", "Testicular inflammation"),
        ("Varicocele", "Various", "Scrotal varices"),
        ("Hydrocele", "Various", "Scrotal fluid"),
        ("Testicular Atrophy", "DC 7523", "Testicular shrinkage"),
        ("Low Testosterone", "Various", "Hypogonadism"),
        ("Infertility Male", "Various", "Reproductive impairment"),
    ],
    "Genitourinary Renal": [
        ("Chronic Kidney Disease Stage 1", "Various", "GFR 90+"),
        ("Chronic Kidney Disease Stage 2", "Various", "GFR 60-89"),
        ("Chronic Kidney Disease Stage 3a", "Various", "GFR 45-59"),
        ("Chronic Kidney Disease Stage 3b", "Various", "GFR 30-44"),
        ("Chronic Kidney Disease Stage 4", "Various", "GFR 15-29"),
        ("Chronic Kidney Disease Stage 5", "Various", "GFR <15"),
        ("End Stage Renal Disease", "Various", "ESRD/dialysis"),
        ("Hemodialysis", "Various", "HD treatment"),
        ("Peritoneal Dialysis", "Various", "PD treatment"),
        ("Kidney Transplant", "DC 7531", "Renal transplant"),
        ("Diabetic Nephropathy", "Various", "DM kidney disease"),
        ("Hypertensive Nephropathy", "Various", "HTN kidney disease"),
        ("IgA Nephropathy", "Various", "Berger's disease"),
        ("Polycystic Kidney", "Various", "PKD"),
        ("Glomerulonephritis", "DC 7502", "Glomerular inflammation"),
        ("Nephrotic Syndrome", "Various", "Protein loss"),
        ("Nephrolithiasis", "DC 7508", "Kidney stones"),
        ("Pyelonephritis Chronic", "DC 7504", "Kidney infection"),
        ("Renal Cyst", "Various", "Simple/complex cyst"),
        ("Renal Cell Carcinoma Residuals", "Various", "Kidney cancer post-treatment"),
    ],
    "Endocrine Thyroid": [
        ("Hypothyroidism", "DC 7903", "Underactive thyroid"),
        ("Hashimoto's Thyroiditis", "Various", "Autoimmune hypothyroid"),
        ("Subclinical Hypothyroid", "Various", "Elevated TSH, normal T4"),
        ("Myxedema", "Various", "Severe hypothyroid"),
        ("Hypothyroid Symptoms", "Various", "Fatigue, weight gain, cold"),
        ("Levothyroxine Treatment", "Various", "T4 replacement"),
        ("Hyperthyroidism", "DC 7900", "Overactive thyroid"),
        ("Graves' Disease", "Various", "Autoimmune hyperthyroid"),
        ("Toxic Nodular Goiter", "DC 7901", "Toxic multinodular"),
        ("Thyroid Storm", "Various", "Life-threatening crisis"),
        ("Hyperthyroid Symptoms", "Various", "Weight loss, tremor, anxiety"),
        ("Methimazole Treatment", "Various", "Antithyroid medication"),
        ("Radioactive Iodine", "Various", "RAI ablation"),
        ("Thyroidectomy", "Various", "Surgical removal"),
        ("Thyroid Nodule", "DC 7902", "Thyroid mass"),
        ("Thyroid Cancer Post-Treatment", "Various", "Cancer residuals"),
        ("Papillary Thyroid Cancer", "Various", "Most common type"),
        ("Follicular Thyroid Cancer", "Various", "Second most common"),
        ("Medullary Thyroid Cancer", "Various", "C-cell origin"),
        ("Anaplastic Thyroid Cancer", "Various", "Aggressive form"),
    ],
    "Endocrine Diabetes Complications": [
        ("Diabetic Retinopathy Non-Proliferative", "Various", "NPDR"),
        ("Diabetic Retinopathy Proliferative", "Various", "PDR"),
        ("Diabetic Macular Edema", "Various", "DME"),
        ("Diabetic Nephropathy Stage I", "Various", "Hyperfiltration"),
        ("Diabetic Nephropathy Stage II", "Various", "Silent phase"),
        ("Diabetic Nephropathy Stage III", "Various", "Microalbuminuria"),
        ("Diabetic Nephropathy Stage IV", "Various", "Macroalbuminuria"),
        ("Diabetic Nephropathy Stage V", "Various", "ESRD"),
        ("Diabetic Neuropathy Sensory", "Various", "Numbness/tingling"),
        ("Diabetic Neuropathy Motor", "Various", "Weakness"),
        ("Diabetic Neuropathy Autonomic", "Various", "Organ dysfunction"),
        ("Diabetic Foot", "Various", "High-risk foot"),
        ("Charcot Foot", "Various", "Neuroarthropathy"),
        ("Diabetic Ulcer", "Various", "Foot wounds"),
        ("Diabetic Amputation", "Various", "Limb loss"),
        ("Diabetic Gastroparesis", "Various", "Stomach paralysis"),
        ("Diabetic Diarrhea", "Various", "Autonomic GI"),
        ("Diabetic Bladder", "Various", "Neurogenic bladder"),
        ("Diabetic Erectile Dysfunction", "Various", "ED from DM"),
        ("Diabetic Cardiomyopathy", "Various", "Heart muscle damage"),
    ],
    "Neurological Headache Disorders": [
        ("Migraine Without Aura", "Various", "Common migraine"),
        ("Migraine With Aura", "Various", "Classic migraine"),
        ("Chronic Migraine", "Various", "15+ days/month"),
        ("Episodic Migraine", "Various", "<15 days/month"),
        ("Vestibular Migraine", "Various", "Dizziness predominant"),
        ("Hemiplegic Migraine", "Various", "Motor weakness"),
        ("Retinal Migraine", "Various", "Visual loss"),
        ("Status Migrainosus", "Various", "72+ hour migraine"),
        ("Tension-Type Headache", "Various", "TTH"),
        ("Chronic TTH", "Various", "15+ days/month"),
        ("Episodic TTH", "Various", "<15 days/month"),
        ("Cluster Headache", "Various", "Trigeminal autonomic"),
        ("Paroxysmal Hemicrania", "Various", "TAC variant"),
        ("SUNCT/SUNA", "Various", "Short-lasting unilateral"),
        ("Hemicrania Continua", "Various", "Continuous one-sided"),
        ("Post-Traumatic Headache", "Various", "TBI-related"),
        ("Medication Overuse Headache", "Various", "Rebound headache"),
        ("Cervicogenic Headache", "Various", "Neck-related"),
        ("New Daily Persistent Headache", "Various", "NDPH"),
        ("Secondary Headache", "Various", "Underlying cause"),
    ],
    "Neurological Movement Disorders": [
        ("Parkinson's Disease", "DC 8004", "Paralysis agitans"),
        ("Parkinson's Tremor", "Various", "Resting tremor"),
        ("Parkinson's Bradykinesia", "Various", "Slow movement"),
        ("Parkinson's Rigidity", "Various", "Muscle stiffness"),
        ("Parkinson's Postural Instability", "Various", "Balance problems"),
        ("Essential Tremor", "Various", "Action tremor"),
        ("Dystonia", "Various", "Sustained muscle contraction"),
        ("Cervical Dystonia", "Various", "Spasmodic torticollis"),
        ("Blepharospasm", "Various", "Eye dystonia"),
        ("Writer's Cramp", "Various", "Task-specific dystonia"),
        ("Huntington's Disease", "Various", "Chorea"),
        ("Tardive Dyskinesia", "Various", "Medication-induced"),
        ("Tics", "Various", "Motor/vocal tics"),
        ("Tourette Syndrome", "Various", "Motor and vocal tics"),
        ("Restless Legs Syndrome", "Various", "RLS/Willis-Ekbom"),
        ("Periodic Limb Movement", "Various", "PLMD"),
        ("Ataxia", "Various", "Coordination impairment"),
        ("Cerebellar Ataxia", "Various", "Cerebellar dysfunction"),
        ("Myoclonus", "Various", "Sudden jerks"),
        ("Multiple System Atrophy", "Various", "MSA"),
    ],
    "Mental Health Mood Disorders": [
        ("Major Depressive Episode", "Various", "MDE criteria"),
        ("Recurrent MDD", "Various", "Multiple episodes"),
        ("Single Episode MDD", "Various", "First episode"),
        ("MDD Mild", "Various", "Few symptoms beyond minimum"),
        ("MDD Moderate", "Various", "Symptoms/functional impairment between mild/severe"),
        ("MDD Severe", "Various", "Most symptoms, marked impairment"),
        ("MDD With Psychotic Features", "Various", "Delusions/hallucinations"),
        ("MDD With Melancholic Features", "Various", "Loss of pleasure, worse AM"),
        ("MDD With Atypical Features", "Various", "Mood reactivity, weight gain"),
        ("MDD With Anxious Distress", "Various", "Prominent anxiety"),
        ("MDD With Seasonal Pattern", "Various", "SAD"),
        ("Persistent Depressive Disorder", "Various", "Dysthymia"),
        ("Bipolar I Disorder", "DC 9432", "Manic episodes"),
        ("Bipolar II Disorder", "DC 9432", "Hypomanic episodes"),
        ("Cyclothymic Disorder", "Various", "Chronic fluctuating"),
        ("Manic Episode", "Various", "Elevated/irritable mood"),
        ("Hypomanic Episode", "Various", "Less severe mania"),
        ("Mixed Features", "Various", "Concurrent depressive/manic"),
        ("Rapid Cycling", "Various", "4+ episodes/year"),
        ("Mood Disorder NOS", "Various", "Unspecified mood"),
    ],
    "Mental Health Trauma/Stressor": [
        ("PTSD Criterion A", "Various", "Traumatic event exposure"),
        ("PTSD Criterion B", "Various", "Intrusion symptoms"),
        ("PTSD Criterion C", "Various", "Avoidance"),
        ("PTSD Criterion D", "Various", "Negative cognitions/mood"),
        ("PTSD Criterion E", "Various", "Arousal/reactivity"),
        ("PTSD Criterion F", "Various", "Duration >1 month"),
        ("PTSD Criterion G", "Various", "Functional impairment"),
        ("PTSD Criterion H", "Various", "Not substance/medical"),
        ("Acute Stress Disorder", "Various", "3 days - 1 month"),
        ("Adjustment Disorder Depressed", "Various", "With depressed mood"),
        ("Adjustment Disorder Anxious", "Various", "With anxiety"),
        ("Adjustment Disorder Mixed", "Various", "Mixed anxiety/depression"),
        ("Adjustment Disorder Conduct", "Various", "With disturbance conduct"),
        ("Adjustment Disorder Unspecified", "Various", "Unspecified type"),
        ("Complex PTSD", "Various", "Prolonged trauma"),
        ("Delayed Expression PTSD", "Various", "6+ months after trauma"),
        ("Dissociative Subtype PTSD", "Various", "Depersonalization/derealization"),
        ("Prolonged Grief Disorder", "Various", "Complicated bereavement"),
        ("Reactive Attachment", "Various", "Childhood neglect"),
        ("Disinhibited Social Engagement", "Various", "Childhood disorder"),
    ],
    "Mental Health Substance Use": [
        ("Alcohol Use Disorder Mild", "Various", "2-3 criteria"),
        ("Alcohol Use Disorder Moderate", "Various", "4-5 criteria"),
        ("Alcohol Use Disorder Severe", "Various", "6+ criteria"),
        ("Alcohol Withdrawal", "Various", "Discontinuation symptoms"),
        ("Delirium Tremens", "Various", "Severe withdrawal"),
        ("Alcohol-Induced Disorders", "Various", "Secondary to alcohol"),
        ("Opioid Use Disorder", "Various", "Opioid addiction"),
        ("Opioid Withdrawal", "Various", "Discontinuation"),
        ("Medication-Assisted Treatment", "Various", "MAT"),
        ("Cannabis Use Disorder", "Various", "Marijuana addiction"),
        ("Stimulant Use Disorder", "Various", "Cocaine/amphetamine"),
        ("Sedative Use Disorder", "Various", "Benzodiazepine/barbiturate"),
        ("Tobacco Use Disorder", "Various", "Nicotine dependence"),
        ("Polysubstance Use", "Various", "Multiple substances"),
        ("Substance-Induced Depression", "Various", "Secondary MH"),
        ("Substance-Induced Anxiety", "Various", "Secondary MH"),
        ("Substance-Induced Psychosis", "Various", "Secondary MH"),
        ("Dual Diagnosis", "Various", "Co-occurring disorders"),
        ("Remission Early", "Various", "3-12 months"),
        ("Remission Sustained", "Various", "12+ months"),
    ],
    "Skin Inflammatory Conditions": [
        ("Atopic Dermatitis", "DC 7806", "AD/eczema"),
        ("Nummular Dermatitis", "Various", "Coin-shaped"),
        ("Dyshidrotic Eczema", "Various", "Pompholyx"),
        ("Stasis Dermatitis", "Various", "Venous insufficiency"),
        ("Asteatotic Eczema", "Various", "Dry skin eczema"),
        ("Seborrheic Dermatitis", "Various", "Scalp/face"),
        ("Contact Dermatitis Allergic", "Various", "Type IV hypersensitivity"),
        ("Contact Dermatitis Irritant", "Various", "Direct irritation"),
        ("Lichen Simplex Chronicus", "Various", "Neurodermatitis"),
        ("Lichen Planus", "DC 7822", "Purple polygonal papules"),
        ("Pityriasis Rosea", "Various", "Herald patch"),
        ("Psoriasis Plaque", "DC 7816", "Most common type"),
        ("Psoriasis Guttate", "DC 7816", "Drop-like"),
        ("Psoriasis Pustular", "DC 7816", "Pustules"),
        ("Psoriasis Inverse", "DC 7816", "Skin folds"),
        ("Psoriasis Nail", "Various", "Nail involvement"),
        ("Psoriasis Scalp", "Various", "Head involvement"),
        ("Rosacea", "Various", "Facial redness"),
        ("Acne Vulgaris", "Various", "Common acne"),
        ("Hidradenitis Suppurativa", "Various", "HS/acne inversa"),
    ],
    "Eye Conditions": [
        ("Cataracts", "DC 6027", "Lens opacity"),
        ("Glaucoma Open Angle", "DC 6012", "Chronic glaucoma"),
        ("Glaucoma Angle Closure", "DC 6012", "Acute glaucoma"),
        ("Macular Degeneration Dry", "DC 6006", "Non-exudative AMD"),
        ("Macular Degeneration Wet", "DC 6006", "Exudative AMD"),
        ("Diabetic Retinopathy", "DC 6006", "DM eye disease"),
        ("Retinal Detachment", "DC 6008", "Retinal separation"),
        ("Corneal Dystrophy", "Various", "Corneal degeneration"),
        ("Keratoconus", "Various", "Corneal thinning"),
        ("Dry Eye Syndrome", "Various", "Keratoconjunctivitis sicca"),
        ("Blepharitis", "Various", "Eyelid inflammation"),
        ("Pterygium", "Various", "Conjunctival growth"),
        ("Diplopia", "DC 6090", "Double vision"),
        ("Visual Field Loss", "DC 6080", "Peripheral vision"),
        ("Central Visual Acuity Loss", "DC 6066", "Central vision"),
        ("Color Vision Deficiency", "Various", "Color blindness"),
        ("Night Blindness", "Various", "Nyctalopia"),
        ("Photophobia", "Various", "Light sensitivity"),
        ("Floaters", "Various", "Vitreous floaters"),
        ("Optic Neuropathy", "DC 6026", "Optic nerve damage"),
    ],
}

def generate_entries():
    """Generate body systems entries"""
    entries = []
    entry_id = 1
    
    for category, items in BODY_SYSTEMS.items():
        for condition, code_ref, description in items:
            entry = {
                "id": f"cavc_body_{entry_id:05d}",
                "source": "cavc",
                "citation": code_ref,
                "title": f"{condition}",
                "content": f"""
BODY SYSTEM CONDITION

SYSTEM: {category}
CONDITION: {condition}
DIAGNOSTIC CODE/REFERENCE: {code_ref}

CLINICAL GUIDANCE:
{description}

RATING CONSIDERATIONS:
Consider functional impairment, treatment requirements, and impact on daily activities when rating {condition.lower()}.
                """.strip(),
                "category": category,
                "hierarchy_level": 2,
                "color_code": "yellow",
                "url": "https://www.ecfr.gov/title-38/chapter-I/part-4",
                "metadata": {
                    "condition": condition,
                    "code": code_ref,
                    "system": category,
                    "description": description,
                    "scraped_date": datetime.now().isoformat()
                }
            }
            entries.append(entry)
            entry_id += 1
    
    return entries

def main():
    print("\n" + "="*80)
    print("⚖️ CAVC BODY SYSTEMS DEEP DIVE DATABASE")
    print("="*80)
    
    entries = generate_entries()
    
    print(f"\n📊 Total entries: {len(entries)}")
    
    # Category breakdown
    categories = {}
    for e in entries:
        cat = e.get('category', 'Unknown')
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\n📋 Category Breakdown:")
    for cat, count in sorted(categories.items()):
        print(f"   {cat}: {count}")
    
    # Save
    output_file = OUTPUT_DIR / "cavc_body_systems_deep.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump({"entries": entries}, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ Saved to: {output_file}")

if __name__ == "__main__":
    main()
