/*
 * Vet-Rate.org - VA Disability Claims Command Center
 * Copyright (C) 2024-2026 Anthony Johnson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 */

import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { ThemeProvider } from "./contexts/ThemeContext";
import { VaAuthProvider } from "./contexts/VaAuthContext";
import VaAuthCallback from "./auth/VaAuthCallback";
import VaSandboxTest from "./components/debug/VaSandboxTest";
import { isVaApiEnabled } from "./config/vaAuth";
import {
  checkSystemCapabilities,
  renderBrowserWarning,
} from "./utils/systemCapabilityCheck";
import { initWebVitals } from "./utils/webVitals";
import "./index.css";
// Affiliation palette accent overrides (autogenerated). Loaded here rather than
// via a CSS @import — a mid-file @import is invalid and the bundler drops it.
import "./generated/palette-themes.css";

// Handles the service worker's "updatefound" event. Extracted to module scope
// (rather than nested inline) to keep function nesting within lint limits.
function handleServiceWorkerUpdateFound(reg) {
  const installing = reg.installing;
  if (!installing) return;
  installing.addEventListener("statechange", () => {
    if (
      installing.state === "installed" &&
      navigator.serviceWorker.controller
    ) {
      window.dispatchEvent(
        new CustomEvent("sw-update-available", {
          detail: {
            accept: () => installing.postMessage({ type: "SKIP_WAITING" }),
          },
        }),
      );
    }
  });
}

// ═══════════════════════════════════════════════════════════════════════════════
// Suppress Browser Extension Errors
// Filter out common extension-related console errors that don't affect the app
// ═══════════════════════════════════════════════════════════════════════════════
const originalError = console.error;
console.error = (...args) => {
  const errorMessage = args[0]?.toString() || "";

  // Filter out known extension-related errors
  if (
    errorMessage.includes("message channel closed") ||
    errorMessage.includes("Extension context invalidated") ||
    errorMessage.includes("asynchronous response")
  ) {
    return; // Suppress these errors - they're from browser extensions, not our code
  }

  // Log all other errors normally
  originalError.apply(console, args);
};

// ═══════════════════════════════════════════════════════════════════════════════
// TECH CHECK - Browser Capability Guard
// Ensures browser supports Crypto API, IndexedDB, and modern JS before loading app
// ═══════════════════════════════════════════════════════════════════════════════
const capabilityResults = checkSystemCapabilities();

if (!capabilityResults.passed) {
  // Browser doesn't meet minimum requirements - show friendly upgrade page
  console.warn(
    "[Tech Check] Browser missing required capabilities:",
    capabilityResults.failedTests,
  );
  renderBrowserWarning(capabilityResults);
} else {
  // All systems go - render the app
  // eslint-disable-next-line no-console
  console.log("[Tech Check] ✓ All browser capabilities verified");

  // Check if this is an OAuth callback or sandbox test route.
  // When the VA API surface is disabled, those routes redirect to "/" so the
  // user never lands on a broken VA component.
  const pathname = window.location.pathname;
  const isOAuthCallback = pathname === "/callback";
  const isSandboxTest = pathname === "/sandbox-test";

  if (!isVaApiEnabled() && (isOAuthCallback || isSandboxTest)) {
    window.history.replaceState(null, "", "/");
  }

  // Helper to render the appropriate component based on route
  const renderRoute = () => {
    if (isVaApiEnabled()) {
      if (isOAuthCallback) return <VaAuthCallback />;
      if (isSandboxTest) return <VaSandboxTest />;
    }
    return <App />;
  };

  ReactDOM.createRoot(document.getElementById("root")).render(
    <React.StrictMode>
      <ThemeProvider>
        <VaAuthProvider>{renderRoute()}</VaAuthProvider>
      </ThemeProvider>
    </React.StrictMode>,
  );

  initWebVitals();

  // Register the service worker for offline shell (Sprint 5 / pwa-privacy).
  // Production-only — dev mode bypasses the SW so HMR works correctly. The
  // SW lives at public/service-worker.js and caches /index.html + core
  // assets so the veteran can reach their saved data on a flaky network.
  if (
    import.meta.env.PROD &&
    typeof navigator !== "undefined" &&
    "serviceWorker" in navigator
  ) {
    window.addEventListener("load", () => {
      navigator.serviceWorker
        .register("/service-worker.js")
        .then((reg) => {
          // eslint-disable-next-line no-console
          console.log("[SW] registered:", reg.scope);

          // Detect new SW installs and surface an "Update available" signal.
          // The SW intentionally does NOT auto-skipWaiting, so the page must
          // accept the update by posting { type: "SKIP_WAITING" }. We dispatch
          // a CustomEvent any component (e.g. a toast) can subscribe to.
          reg.addEventListener("updatefound", () =>
            handleServiceWorkerUpdateFound(reg),
          );
        })
        .catch((err) => {
          console.warn("[SW] registration failed:", err.message);
        });

      // After the SW activates a new version, reload once so the new bundle
      // is the one running. Guarded so it only fires after a real change.
      let reloaded = false;
      navigator.serviceWorker.addEventListener("controllerchange", () => {
        if (reloaded) return;
        reloaded = true;
        window.location.reload();
      });
    });
  }
}
